// Reel 3 « Andorre, le petit pays mystérieux » — 100 % B-roll, kinetic text = narration. Higgsedit v0.14, 1080x1920 @ 30 fps.
// Generated by gen_edit.py (screens, shots). Audio (original score + SFX, audio/music.py) is muxed after render.
// Safe zone for text: x 90–990, y 300–1450 (Reels UI covers the top ~250 px, the bottom ~420 px and the right rail).
import { createRequire } from "node:module";

const D = /*__DATA__*/null;
const W = 1080, H = 1920, FONT = "Montserrat";
const C = { fg: "#FFFFFF", bk: "#0B0B0B", acc: D.ACC, dim: "#FFFFFFB3" };
const EASE = [0.2, 0.8, 0.2, 1];
const SPRING = { kind: "spring", stiffness: 320, damping: 20 };
const MEDIA = "/home/user/w3";
const DROP = 16.0;

const require = createRequire("/opt/fable/package.json");
const { GlobalFonts, createCanvas } = require("@napi-rs/canvas");
GlobalFonts.registerFromPath(`${MEDIA}/reel/fonts/montserrat-800.woff2`, "M800");
GlobalFonts.registerFromPath(`${MEDIA}/reel/fonts/montserrat-600.woff2`, "M600");
const ctx = createCanvas(4, 4).getContext("2d");
const mw = (s, size, wt = 800) => { ctx.font = `${size}px ${wt === 800 ? "M800" : "M600"}`; return ctx.measureText(s).width; };
const tw = (s, size, wt = 800) => Math.ceil(mw(s, size, wt) * 1.04) + 6;

// Grade: exposure, saturation, contrast, RGB tint, vignette, fine grain. Dark (mystery) before the drop, bright after.
const GRADE = `vec4 pixel(vec2 uv){
  vec4 c = texture(u_src, uv);
  vec3 g = c.rgb * u_exp;
  float l = dot(g, vec3(0.2126, 0.7152, 0.0722));
  g = mix(vec3(l), g, u_sat);
  g = (g - 0.5) * u_con + 0.5;
  g *= vec3(u_r, u_g, u_b);
  float d = distance(uv, vec2(0.5));
  g *= 1.0 - u_vig * smoothstep(0.25, 0.85, d);
  float n = fract(sin(dot(floor(uv * u_resolution) + floor(u_time * 30.0) * 17.0, vec2(12.9898, 78.233))) * 43758.5453) - 0.5;
  return vec4(clamp(g + n * 0.025, 0.0, 1.0) * c.a, c.a);
}`;
const DARK = { exp: 0.76, sat: 0.5, con: 1.12, r: 0.9, g: 0.97, b: 1.08, vig: 0.75 };
const BRIGHT = { exp: 1.04, sat: 1.18, con: 1.06, r: 1.04, g: 1.0, b: 0.95, vig: 0.35 };
const WARM = { exp: 1.0, sat: 1.15, con: 1.08, r: 1.08, g: 0.99, b: 0.9, vig: 0.45 };
const grade = (p) => ({ kind: "shader", params: { glsl: GRADE, ...p } });

const K = (...pairs) => pairs.map(([at, value, easing]) => ({ at, value, ...(easing ? { easing } : {}) }));
const drawX = (w, h, at, dur) => ({ mask: { shape: "rectangle", x: -8, y: -6, width: 2, height: h + 12 },
  anim: { property: "maskWidth", keyframes: K([0, 2, "hold"], [Math.max(at, 0.001), 2, EASE], [at + dur, 2 * w + 24]) } });

export default async ({ project, text, rect, media, path, frame }) => {
  const p = await project({ dir: "reel", size: `${W}x${H}`, fps: 30, background: C.bk });
  const files = {};
  for (const [k, s] of Object.entries(D.shots)) if (!files[s.file]) files[s.file] = await p.add(`${MEDIA}/${s.file}`);

  // Higgsedit's script lane allocator mis-maps lanes when several composes share a start time, so every layer is ONE
  // full-length compose (distinct lane) whose children carry absolute at/duration (parent starts at 0).
  const LAYERS = {};
  const ORDER = ["shots", "legibility", "shade", "map", "text", "underline", "fx", "progress"];
  const layerOf = (name) => name.startsWith("shot") ? "shots" : name.startsWith("text") ? "text" : name === "map" ? "map"
    : name === "end darken" ? "shade" : ["legibility", "underline", "progress"].includes(name) ? name : "fx";
  const put = (node, o) => (LAYERS[layerOf(o.name)] ||= []).push(
    frame({ x: 0, y: 0, width: W, height: H, layout: "none", at: o.at, duration: o.dur }, Array.isArray(node) ? node : [node]));

  // ================= picture: one media node per run of screens sharing a shot =================
  const runs = [];
  for (const s of D.screens) {
    const last = runs[runs.length - 1];
    if (last && last.shot === s.shot) last.t1 = s.t1; else runs.push({ shot: s.shot, t0: s.t0, t1: s.t1, n: s.n });
  }
  for (const r of runs) {
    const sh = D.shots[r.shot], dur = r.t1 - r.t0, bright = r.t0 >= DROP;
    const g = r.t0 >= 46 ? WARM : bright ? BRIGHT : DARK;
    // bright section: punch-in 1.12 -> 1.0 on every cut (0.35 s), then a slow push; dark: slow push only
    const scaleKeys = bright
      ? K([0, 1.12, EASE], [0.35, 1.0, "linear"], [dur - 0.001, 1.0 + 0.012 * dur])
      : K([0, 1.0, "linear"], [dur - 0.001, 1.0 + 0.02 * dur]);
    const z = sh.zoom || 1;   // zoom > 1 crops the bottom edge (top-anchored), e.g. to drop a lens artefact
    const kids = [media({ file: files[sh.file], x: -(W * z - W) / 2, y: 0, width: W * z, height: H * z, fit: "cover", trimStart: sh.from, muted: true,
      effects: [grade(g)], animate: [{ property: "scale", keyframes: scaleKeys }] })];
    if (sh.blur) kids[0] = media({ file: files[sh.file], x: 0, y: 0, width: W, height: H, fit: "cover", trimStart: sh.from, muted: true,
      effects: [grade({ ...g, exp: 0.4 })], animate: [{ property: "scale", keyframes: scaleKeys }, { property: "blur", keyframes: K([0, 0, EASE], [0.5, sh.blur]) }] });
    put(frame({ x: 0, y: 0, width: W, height: H, layout: "none", clip: true, ...(bright ? { motionBlur: { samples: 5, shutter: 0.5 } } : {}) }, kids),
      { at: r.t0, dur, name: `shot ${r.n} ${r.shot}` });
  }
  // legibility: soft dark band behind the text block (y 560–1300), whole reel
  put(rect({ x: 0, y: 0, width: W, height: H, fill: { kind: "linear", angle: 180, stops: [
    { offset: 0, color: "#000000", opacity: 0.0 }, { offset: 0.28, color: "#000000", opacity: 0.28 }, { offset: 0.5, color: "#000000", opacity: 0.38 },
    { offset: 0.7, color: "#000000", opacity: 0.28 }, { offset: 1, color: "#000000", opacity: 0.1 }] } }), { at: 0, dur: D.DUR, name: "legibility" });

  // ================= screen 3: map drawn from Natural Earth outlines =================
  {
    const s = D.screens.find((x) => x.shot === "map"), M = D.map, dur = s.t1 - s.t0, top = 300;
    const fr = drawX(M.W, M.H, 0.05, 0.7), es = drawX(M.W, M.H, 0.05, 0.7);
    const [bx0, by0, bx1, by1] = M.andorra_bbox;
    const aw = bx1 - bx0 + 20, ah = by1 - by0 + 20;
    const ad = drawX(aw, ah, 0.35, 0.6);
    put(frame({ x: 0, y: top, width: W, height: M.H, layout: "none" }, [
      path({ x: 0, y: 0, width: M.W, height: M.H, d: M.fra, stroke: { width: 4, color: "#FFFFFF80", cap: "round" }, mask: fr.mask, animate: [fr.anim] }),
      path({ x: 0, y: 0, width: M.W, height: M.H, d: M.esp, stroke: { width: 4, color: "#FFFFFF80", cap: "round" }, mask: es.mask, animate: [es.anim] }),
      path({ x: 0, y: 0, width: M.W, height: M.H, d: M.andorra, stroke: { width: 6, color: C.acc, cap: "round" },
        mask: { shape: "rectangle", x: bx0 - 18, y: by0 - 10, width: 2, height: ah }, animate: [ad.anim] }),
      path({ x: 0, y: 0, width: M.W, height: M.H, d: M.andorra, fill: C.acc,
        animate: [{ property: "opacity", keyframes: K([0, 0, "hold"], [0.8, 0, EASE], [1.1, 0.35]) }] }),
      text("FRANCE", { x: 640, y: 120, width: tw("FRANCE", 44, 600), height: 60, fontFamily: FONT, fontWeight: 600, fontSize: 44, color: "#FFFFFFCC", letterSpacing: 6,
        animate: [{ property: "opacity", keyframes: K([0, 0, "hold"], [0.3, 0, EASE], [0.6, 1]) }] }),
      text("ESPAGNE", { x: 150, y: 640, width: tw("ESPAGNE", 44, 600) + 40, height: 60, fontFamily: FONT, fontWeight: 600, fontSize: 44, color: "#FFFFFFCC", letterSpacing: 6,
        animate: [{ property: "opacity", keyframes: K([0, 0, "hold"], [0.4, 0, EASE], [0.7, 1]) }] }),
    ]), { at: s.t0, dur, name: "map" });
  }

  // ================= kinetic text: one block per screen =================
  const SIZE_MAIN = 74, SIZE_ACC_LINE = 150, GAP = 14;
  for (const s of D.screens) {
    const dur = s.t1 - s.t0, isMap = s.shot === "map", reveal = s.n === 9, cta = s.n >= 21;
    const lines = s.lines.map((ln) => {
      const onlyAcc = ln.length === 1 && ln[0].acc;
      const size = reveal ? 176 : onlyAcc ? (cta ? 190 : SIZE_ACC_LINE) : SIZE_MAIN;
      // segments sit at the measured advance of the text before them (kerning-exact, no double spaces)
      let pre = "";
      const segs = ln.map((g) => { const lead = g.t.match(/^ */)[0], s = g.t.slice(lead.length);   // a leading space is not drawn: fold it into x
        const x = mw(pre + lead, size); pre += g.t; return { ...g, t: s, x, w: tw(s, size) + 24 }; });
      return { segs, size, onlyAcc, w: Math.ceil(mw(pre, size)), h: Math.round(size * 1.18) };
    });
    const total = lines.reduce((a, l) => a + l.h, 0) + GAP * (lines.length - 1);
    let yy = isMap ? 1090 : Math.round(900 - total / 2);
    const nodes = [];
    lines.forEach((l, i) => {
      const at = (s.n === 22 ? 0 : 0.06 + i * 0.16), x0 = Math.round((W - l.w) / 2);
      const segNodes = [];
      for (const g of l.segs) {
        segNodes.push(text(g.t, { x: Math.round(g.x), y: 0, width: g.w, height: l.h, fontFamily: FONT, fontWeight: 800, fontSize: l.size, color: g.acc ? C.acc : C.fg,
          ...(l.onlyAcc ? {} : { motion: { by: "word", from: { opacity: 0, y: 26 }, at: 0, duration: 0.28, overlap: 0.55, easing: "ease-out" } }),
          shadow: { x: 0, y: 4, blur: 18, color: "#00000099" } }));
      }
      const lineDur = dur - at;
      const exitKeys = s.n === 22 ? [] : [[lineDur - 0.12, 1, EASE], [lineDur - 0.001, 0]];
      if (l.onlyAcc && s.n !== 22) {
        nodes.push(frame({ x: x0, y: yy, width: l.w + 30, height: l.h, layout: "none", origin: "center", at, duration: lineDur,
          motion: { enter: { from: { scale: reveal ? 1.35 : 0.55 }, duration: reveal ? 0.6 : 0.45, easing: SPRING } },
          animate: [{ property: "opacity", keyframes: K([0, 0, EASE], [0.08, 1, "hold"], ...exitKeys) }] }, segNodes));
      } else {
        nodes.push(frame({ x: x0, y: yy, width: l.w + 30, height: l.h, layout: "none", at, duration: lineDur,
          ...(exitKeys.length ? { animate: [{ property: "opacity", keyframes: K([0, 1, "hold"], ...exitKeys) }] } : {}) }, segNodes));
      }
      yy += l.h + GAP;
    });
    put(frame({ x: 0, y: 0, width: W, height: H, layout: "none" }, nodes), { at: s.t0, dur, name: `text ${s.n}` });
  }

  // ================= transitions & accents =================
  // drop: white flash 0.45 s + chromatic "lift" on the reveal
  put(rect({ x: 0, y: 0, width: W, height: H, fill: "#FFFFFF", animate: [{ property: "opacity", keyframes: K([0, 0.95, EASE], [0.45, 0]) }] }),
    { at: DROP, dur: 0.46, name: "flash drop" });
  // dark section: 0.18 s dip from black on each cut (mystery breathing)
  for (const s of D.screens.filter((x) => x.t0 > 0 && x.t0 < DROP))
    put(rect({ x: 0, y: 0, width: W, height: H, fill: C.bk, animate: [{ property: "opacity", keyframes: K([0, 0.85, EASE], [0.2, 0]) }] }),
      { at: s.t0, dur: 0.21, name: `dip ${s.n}` });
  // fade in from black at 0
  put(rect({ x: 0, y: 0, width: W, height: H, fill: C.bk, animate: [{ property: "opacity", keyframes: K([0, 1, EASE], [0.6, 0]) }] }), { at: 0, dur: 0.61, name: "fade in" });
  // CTA: accent underline under LISTE on screens 21–22, end: darken the last shot
  {
    const s = D.screens.find((x) => x.n === 21), w = tw("LISTE", 190) - 20;
    const d = drawX(w, 14, 0.35, 0.35);
    put(rect({ x: (W - w) / 2, y: 1020, width: w, height: 14, radius: 7, fill: C.acc, mask: d.mask, animate: [d.anim] }), { at: s.t0, dur: D.DUR - s.t0, name: "underline" });
    const e = D.screens.find((x) => x.n === 22);
    put(rect({ x: 0, y: 0, width: W, height: H, fill: C.bk, animate: [{ property: "opacity", keyframes: K([0, 0, EASE], [0.3, 0.45, "hold"], [e.t1 - e.t0 - 0.5, 0.45, EASE], [e.t1 - e.t0 - 0.001, 1]) }] }),
      { at: e.t0, dur: e.t1 - e.t0, name: "end darken" });
  }
  // thin progress bar at the very top of the safe area (accent), whole reel
  put(rect({ x: 0, y: 0, width: W, height: 8, fill: C.acc, mask: { shape: "rectangle", x: -1, y: -2, width: 2, height: 12 },
    animate: [{ property: "maskWidth", keyframes: K([0, 2, "linear"], [D.DUR - 0.001, 2 * W + 4]) }] }), { at: 0, dur: D.DUR, name: "progress" });

  for (const k of ORDER) if (LAYERS[k]) p.compose(frame({ x: 0, y: 0, width: W, height: H, layout: "none" }, LAYERS[k]), { at: 0, dur: D.DUR, name: k });

  const mode = process.env.REEL_MODE || "frames";
  if (mode === "frames") {
    const only = process.env.REEL_TIMES ? process.env.REEL_TIMES.split(",").map(Number) : D.sheet;
    for (const t of only) await p.frame(t, `renders/f_${t.toFixed(2)}.png`);
  } else if (mode === "draft") {
    await p.render("renders/draft.mp4", { draft: true, concurrency: 3 });
  } else if (mode === "master") {
    await p.render("renders/master.mp4", { depth: 8, bitrate: 12_000_000, concurrency: 3 });
  }
};
