// Reel 6 « Impôts & OnlyFans » — talking head + real-time motion design. Higgsedit v0.14 (f39e3bc5882b), 1080x1920 @ 60 fps.
// Generated by gen_edit.py (captions, trigger times, punch-ins). Every time is on the jump-cut timeline of cut.mp4.
// Zones: face y 135–776 · free zone y 790–1310 (windows) / 800–1240 (cards) · captions y 1300 (1420 under a window, left column next to the phone).
import { createRequire } from "node:module";
import fs from "node:fs";

const D = /*__DATA__*/null;
const T = D.T, A = D.A;
const W = 1080, H = 1920, FPS = 60, MONT = "Montserrat", INTER = "Inter";
const C = { acc: "#FFC83D", acc2: "#E5484D", white: "#FFFFFF", black: "#0B0B0B", ok: "#34C759", grey: "#8E8E93", line: "#0000001A",
  bar: "#F2F2F4", field: "#E9E9EC", glass: "#FFFFFF14", glassLine: "#FFFFFF2E", pill: "#0B0B0BCC", ink: "#1D1D1F" };
const EASE = [0.2, 0.8, 0.2, 1];                                  // the one curve of this short
const SPRING = { kind: "spring", stiffness: 300, damping: 22 };
const SHADOW = { x: 0, y: 16, blur: 48, color: "#00000059" };     // the one shadow (0 / 16 / 48, 35 %)
const MEDIA = "/home/user/w6";

// Measure with the faces the renderer uses (registered in the project by `higgsedit fonts add`).
const require = createRequire("/opt/fable/package.json");
const { GlobalFonts, createCanvas } = require("@napi-rs/canvas");
const FONTS = fs.existsSync(`${MEDIA}/reel/fonts`) ? fs.readdirSync(`${MEDIA}/reel/fonts`) : [];
const reg = (re, alias) => { const f = FONTS.find((n) => re.test(n)); if (f) GlobalFonts.registerFromPath(`${MEDIA}/reel/fonts/${f}`, alias); };
reg(/montserrat.*800/i, "M800"); reg(/inter.*400/i, "I400"); reg(/inter.*600/i, "I600"); reg(/inter.*700/i, "I700");
const ctx = createCanvas(4, 4).getContext("2d");
const raw = (s, size, face = "M800") => { ctx.font = `${size}px ${face}`; return ctx.measureText(s).width; };
const tw = (s, size, face = "M800") => Math.ceil(raw(s, size, face) * 1.04) + 8;

// Grade: contrast +5 %, saturation −5 %, vignette 15 %, 35 mm grain 0.03.
const GRADE = `vec4 pixel(vec2 uv){
  vec4 c = texture(u_src, uv);
  vec3 g = c.rgb;
  float l = dot(g, vec3(0.2126, 0.7152, 0.0722));
  g = mix(vec3(l), g, u_sat);
  g = (g - 0.5) * u_con + 0.5;
  vec2 d = (uv - 0.5) * vec2(1.0, 1.35);
  g *= 1.0 - u_vig * smoothstep(0.25, 0.85, length(d));
  float n = fract(sin(dot(floor(uv * u_resolution) + floor(u_time * 60.0) * 17.0, vec2(12.9898, 78.233))) * 43758.5453) - 0.5;
  return vec4(clamp(g + n * u_amt, 0.0, 1.0) * c.a, c.a);
}`;
const grade = (amt = 0.03) => ({ kind: "shader", params: { glsl: GRADE, amt, con: 1.05, sat: 0.95, vig: 0.15 } });

// ---------- small builders ----------
const clean = (o) => Object.fromEntries(Object.entries(o).filter(([, v]) => v !== undefined));
const K = (...pairs) => pairs.map(([at, value, easing]) => ({ at, value, ...(easing ? { easing } : {}) }));
const io = (dur, din = 0.15, dout = 0.2) => ({ property: "opacity", keyframes: K([0, 0, EASE], [din, 1, "hold"], [dur - dout - 0.001, 1, EASE], [dur - 0.001, 0]) });
const shake = (t, amp = 3) => ({ property: "offsetX", keyframes: K([0, 0, "hold"], [t, 0, "linear"], [t + 0.04, amp, "linear"], [t + 0.08, -amp, "linear"], [t + 0.12, amp, "linear"], [t + 0.16, -amp, "linear"], [t + 0.2, 0]) });
// stroke reveal along x / y (mask grows from the path origin)
const drawX = (w, h, at, dur) => ({ mask: { shape: "rectangle", x: -8, y: -6, width: 2, height: h + 12 },
  anim: { property: "maskWidth", keyframes: K([0, 2, "hold"], [Math.max(at, 0.001), 2, EASE], [at + dur, 2 * w + 24]) } });
const circleD = (r, p = 0) => { const k = 0.5523 * r, c = r + p;
  return `M ${c + r} ${c} C ${c + r} ${c + k} ${c + k} ${c + r} ${c} ${c + r} C ${c - k} ${c + r} ${c - r} ${c + k} ${c - r} ${c} C ${c - r} ${c - k} ${c - k} ${c - r} ${c} ${c - r} C ${c + k} ${c - r} ${c + r} ${c - k} ${c + r} ${c} Z`; };

export default async ({ project, text, rect, media, path, frame, icon }) => {
  const p = await project({ dir: "reel", size: `${W}x${H}`, fps: FPS, background: C.black });
  const v = await p.add(`${MEDIA}/cut.mp4`);
  const img = {};
  for (const n of ["impots", "urssaf", "urssaf_iphone", "onlyfans", "uk", "fr"]) img[n] = await p.add(`${MEDIA}/${n}.png`);
  const notif = await p.add(`${MEDIA}/notification.mov`);
  const broll = await p.add(`${MEDIA}/broll_balcon.mp4`);
  const S = (t) => Math.round(t * FPS) / FPS;                       // compose boundaries on the frame grid (the track planner checks exact overlaps)
  const DUR = S(D.DUR);

  // ---------- typography helpers ----------
  const T_ = (s, o = {}) => { const size = o.size || 44, face = o.face || "M800", w = o.width || tw(s, size, face);
    const fam = face[0] === "M" ? MONT : INTER, wt = face[0] === "M" ? 800 : Number(face.slice(1));
    return text(s, clean({ x: o.x ?? 0, y: o.y ?? 0, width: w, height: Math.round(size * 1.3), align: o.align || "left", fontFamily: fam, fontWeight: wt,
      fontSize: size, color: o.color || C.white, at: o.at, duration: o.duration, animate: o.animate, shadow: o.shadow, letterSpacing: o.ls })); };
  // element shell: frame with spring entrance (scale 0.9 -> 1) + fade, closing scale 0.96 + fade 0.2 s
  const el = (o, kids) => { const dur = o.duration;
    return frame(clean({ name: o.name, x: o.x, y: o.y, width: o.w, height: o.h, layout: "none", origin: "center", at: o.at || undefined, duration: dur,
      motion: { enter: { from: { scale: o.from ?? 0.9, ...(o.fromY ? { y: o.fromY } : {}), ...(o.fromRot ? { rotation: o.fromRot } : {}) }, duration: 0.5, easing: SPRING },
        exit: { to: { scale: 0.96 }, duration: 0.2, easing: EASE } },
      motionBlur: o.blur ? { samples: 6, shutter: 0.5 } : undefined,
      animate: [io(dur, 0.12, 0.2), ...(o.animate || [])] }), kids); };
  // glass card: the footage itself, blurred 24 px, under a white 8 % veil and a hairline (« verre, flou pré-rendu 24 px »)
  const glass = (x, y, w, h, absAt) => [
    rect({ x: 0, y: 0, width: w, height: h, radius: 20, fill: "#0B0B0B40", shadow: SHADOW }),
    frame({ x: 0, y: 0, width: w, height: h, layout: "none", clip: true, radius: 20 },
      [media({ file: v, x: -x, y: -y, width: W, height: H, fit: "fill", trimStart: absAt, effects: [{ kind: "blur", params: { px: 24 } }] })]),
    rect({ x: 0, y: 0, width: w, height: h, radius: 20, fill: C.glass, strokeColor: C.glassLine, strokeWidth: 2 }),
  ];
  const card = (w, h) => rect({ x: 0, y: 0, width: w, height: h, radius: 20, fill: C.white, strokeColor: C.line, strokeWidth: 1, shadow: SHADOW });
  const pill = (s, o) => { const size = o.size || 30, face = o.face || "I600", w = tw(s, size, face) + 44, h = Math.round(size * 1.3) + 22;
    return frame(clean({ x: o.cx !== undefined ? o.cx - w / 2 : o.x, y: o.y, width: w, height: h, layout: "none", at: o.at, duration: o.duration, animate: o.animate }),
      [rect({ x: 0, y: 0, width: w, height: h, radius: h / 2, fill: o.bg || C.pill }), T_(s, { size, face, x: 22, y: 11, color: o.color || C.white })]); };
  const ring = (cx, cy, r, at, color = C.acc) => path({ x: cx - r - 6, y: cy - r - 6, width: 2 * r + 12, height: 2 * r + 12, d: circleD(r, 6), stroke: { width: 6, color }, at, duration: 0.45,
    animate: [{ property: "scale", keyframes: K([0, 0.85, EASE], [0.4, 1.45]) }, { property: "opacity", keyframes: K([0, 0.9, EASE], [0.42, 0]) }] });
  const check = (x, y, at, s = 64) => { const d = drawX(36, 30, at + 0.05, 0.25);
    return [rect({ x, y, width: s, height: s, radius: 16, fill: "#FFFFFF1F", strokeColor: "#FFFFFF59", strokeWidth: 2 }),
      rect({ x, y, width: s, height: s, radius: 16, fill: C.ok, at, animate: [{ property: "opacity", keyframes: K([0, 0, EASE], [0.08, 1]) }, { property: "scale", keyframes: K([0, 0.7, EASE], [0.2, 1]) }] }),
      path({ x: x + (s - 36) / 2, y: y + (s - 30) / 2, width: 36, height: 30, d: "M 3 16 L 13 26 L 33 4", stroke: { width: 6, color: C.white, cap: "round" }, mask: d.mask, animate: [d.anim] })]; };
  const cross = (x, y, w, h, at) => { const a = drawX(w, h, at, 0.14), b = drawX(w, h, at + 0.11, 0.14);
    return [path({ x, y, width: w, height: h, d: `M 4 4 L ${w - 4} ${h - 4}`, stroke: { width: 9, color: C.acc2, cap: "round" }, mask: a.mask, animate: [a.anim] }),
      path({ x, y, width: w, height: h, d: `M 4 ${h - 4} L ${w - 4} 4`, stroke: { width: 9, color: C.acc2, cap: "round" }, mask: b.mask, animate: [b.anim] })]; };
  // counter leaf (fixed-size layout-none frame, one static text): value rolls from `from` to `to`
  let cid = 0;
  const counter = (o) => { const name = `cnt${cid++}`, size = o.size, face = o.face || "M800", w = o.w || tw(o.final, size, face), h = Math.round(size * 1.25);
    return frame(clean({ x: o.x, y: o.y, width: w, height: h, layout: "none", at: o.at, duration: o.duration,
      motion: { timeline: { at: o.start, duration: o.roll || 0.5, easing: EASE, targets: [{ target: name, counter: { from: o.from, to: o.to, decimals: 0, prefix: o.prefix || "", suffix: o.suffix || "" } }] } } }),
      [frame({ name, x: 0, y: 0, width: w, height: h, layout: "none" }, [text(o.final, { x: 0, y: 0, width: w, height: h, align: o.align || "left", fontFamily: face[0] === "M" ? MONT : INTER,
        fontWeight: face[0] === "M" ? 800 : Number(face.slice(1)), fontSize: size, color: o.color || C.white })])]); };
  // dots travelling along a straight connector (« le flux circule »)
  const flowDots = (x1, y1, x2, y2, at, dur, color = C.acc, P = 0.7) => { const out = [];
    for (let i = 0; i < 3; i++) { const start = at + (i * P) / 3, reps = Math.floor((dur - (start - at)) / (P + 0.001));
      if (reps < 1) continue;
      const anim = [{ property: "offsetX", keyframes: K([0, 0, "linear"], [P, x2 - x1, "hold"], [P + 0.001, 0]), ...(reps > 1 ? { repeat: reps } : {}) },
        { property: "offsetY", keyframes: K([0, 0, "linear"], [P, y2 - y1, "hold"], [P + 0.001, 0]), ...(reps > 1 ? { repeat: reps } : {}) },
        { property: "opacity", keyframes: K([0, 0, "linear"], [0.12, 1, "hold"], [P - 0.12, 1, "linear"], [P, 0, "hold"], [P + 0.001, 0]), ...(reps > 1 ? { repeat: reps } : {}) }];
      out.push(rect({ x: x1 - 7, y: y1 - 7, width: 14, height: 14, radius: 7, fill: color, at: start, duration: reps * (P + 0.001), animate: anim })); }
    return out; };

  // ---------- macOS / browser window (light mode) ----------
  // content: { img, sx (display scale of the capture), ox, oy (capture offset), zoom?: {at, k, ax, ay} , hl?: {x,y,w,h,at} }
  const window_ = (o) => {
    const w = o.w || 820, h = o.h || 520, browser = !!o.url, top = browser ? 96 : 52, ch = h - top;
    const kids = [rect({ x: 0, y: 0, width: w, height: h, radius: 20, fill: C.white, strokeColor: C.line, strokeWidth: 1, shadow: SHADOW }),
      rect({ x: 0, y: 0, width: w, height: top, radius: 20, fill: C.bar }), rect({ x: 0, y: top - 20, width: w, height: 20, fill: C.bar }),
      rect({ x: 0, y: top - 1, width: w, height: 1, fill: C.line }),
      ...["#FF5F57", "#FEBC2E", "#28C840"].map((c, i) => rect({ x: 22 + i * 24, y: 19, width: 14, height: 14, radius: 7, fill: c }))];
    if (browser) {
      const tabW = 250;
      kids.push(rect({ x: 104, y: 8, width: tabW, height: 40, radius: 10, fill: C.white }),
        T_(o.tab, { size: 18, face: "I600", x: 120, y: 17, color: C.ink, width: tabW - 30 }),
        rect({ x: 20, y: 54, width: w - 40, height: 34, radius: 10, fill: C.field }),
        icon("lock", { x: 32, y: 62, size: 18, color: C.grey, strokeWidth: 2 }));
      // the URL types itself at 40 ms per letter (mask grows letter by letter, hold keys), then the page appears
      const size = 20, ux = 58, uy = 59, t0 = o.typeAt, step = 0.04;
      const keys = [{ at: 0, value: 1, easing: "hold" }];
      for (let i = 1; i <= o.url.length; i++) keys.push({ at: t0 + (i - 1) * step, value: 2 * (raw(o.url.slice(0, i), size, "I400") + 1), easing: "hold" });
      keys.push({ at: t0 + o.url.length * step + 0.01, value: 2 * (raw(o.url, size, "I400") + 6) });
      kids.push(text(o.url, { x: ux, y: uy, width: tw(o.url, size, "I400"), height: 26, fontFamily: INTER, fontWeight: 400, fontSize: size, color: C.ink,
        mask: { shape: "rectangle", x: -1, y: -4, width: 1, height: 34 }, animate: [{ property: "maskWidth", keyframes: keys }] }),
      // caret
      rect({ x: ux, y: uy + 2, width: 2, height: 22, fill: C.ink, at: Math.max(0.01, t0 - 0.15), duration: o.url.length * step + 0.3,
        animate: [{ property: "offsetX", keyframes: [...Array(o.url.length + 1).keys()].map((i) => ({ at: 0.15 + i * step, value: i ? raw(o.url.slice(0, i), size, "I400") + 2 : 0, easing: "hold" })) }] }));
    } else kids.push(T_(o.title, { size: 20, face: "I600", x: 0, y: 14, width: w, align: "center", color: C.ink }));
    // content: capture (clipped), optional zoom towards an anchor + highlighter that follows the zoom
    const ct = o.content, pageAt = browser ? o.typeAt + o.url.length * 0.04 + 0.08 : 0.12;
    const zk = ct.zoom, z = (x0, y0, t0) => (zk ? [{ property: "scale", keyframes: K([0, 1, "hold"], [zk.at - t0, 1, EASE], [zk.at - t0 + 0.45, zk.k]) },
      { property: "offsetX", keyframes: K([0, 0, "hold"], [zk.at - t0, 0, EASE], [zk.at - t0 + 0.45, (x0 - zk.ax) * (zk.k - 1)]) },
      { property: "offsetY", keyframes: K([0, 0, "hold"], [zk.at - t0, 0, EASE], [zk.at - t0 + 0.45, (y0 - zk.ay) * (zk.k - 1)]) }] : []);
    const inner = [media({ file: ct.img, x: ct.ox, y: ct.oy, width: ct.iw * ct.sx, height: ct.ih * ct.sx, fit: "fill", at: pageAt,
      animate: [{ property: "opacity", keyframes: K([0, 0, EASE], [0.2, 1]) }, ...z(ct.ox, ct.oy, pageAt)] })];
    if (ct.hl) { const hl = ct.hl, d = drawX(hl.w, hl.h, 0.001, 0.3);
      inner.push(rect({ x: hl.x, y: hl.y, width: hl.w, height: hl.h, radius: 6, fill: "#FFC83D4D", at: hl.at, mask: d.mask, animate: [d.anim, ...z(hl.x, hl.y, hl.at)] })); }
    kids.push(frame({ x: 0, y: top, width: w, height: ch, layout: "none", clip: true }, [rect({ x: 0, y: 0, width: w, height: ch, fill: "#FAFAFA" }), ...inner]),
      rect({ x: 0, y: h - 20, width: w, height: 20, fill: "#00000000" }));
    return kids;
  };
  // window shell with raw tracks (needed when it recedes behind a second element: one owner per channel)
  const winShell = (o, kids) => { const dur = o.duration, r = o.recede;
    const sc = [[0, 0.9, EASE], [0.2, 1.012, EASE], [0.32, 1]];
    if (r !== undefined) sc.push([r, 1, EASE], [r + 0.25, 0.96, "hold"]);
    sc.push([dur - 0.2, r !== undefined ? 0.96 : 1, EASE], [dur - 0.001, r !== undefined ? 0.94 : 0.96]);
    const op = [[0, 0, EASE], [0.12, 1, "hold"]];
    if (r !== undefined) op.push([r, 1, EASE], [r + 0.25, 0.7, "hold"]);
    op.push([dur - 0.2, r !== undefined ? 0.7 : 1, EASE], [dur - 0.001, 0]);
    return frame(clean({ x: o.x, y: o.y, width: o.w, height: o.h, layout: "none", origin: "center", at: o.at || undefined, duration: dur,
      animate: [{ property: "scale", keyframes: K(...sc) }, { property: "opacity", keyframes: K(...op) }] }), kids); };
  // logo / icon tile 160 px (radius 36, white, shadow), accent ring on entrance, optional label pill under it
  const tile = (o) => { const kids = [rect({ x: 0, y: 0, width: 160, height: 160, radius: 36, fill: C.white, shadow: SHADOW })];
    if (o.img) kids.push(media({ file: o.img, x: (160 - o.iw) / 2, y: (160 - o.ih) / 2, width: o.iw, height: o.ih, fit: "fill", ...(o.round ? { radius: o.round } : {}) }));
    if (o.icon) kids.push(icon(o.icon, { x: 32, y: 32, size: 96, color: C.black, strokeWidth: 2 }));
    if (o.label) { const lw = tw(o.label, 28, "I600") + 40; kids.push(pill(o.label, { x: (160 - lw) / 2, y: 176, size: 28 })); }
    return el({ x: o.x, y: o.y, w: 160, h: o.label ? 236 : 160, at: o.at, duration: o.duration, from: 0.6, animate: o.animate },
      [...kids, ...(o.noRing ? [] : [ring(80, 80, 92, 0.05, o.ringColor || C.acc)])]); };

  // ================= spine: picture + final mix (voice + sound design) =================
  p.cut(v, { from: 0, dur: DUR, fit: "cover" });

  // ================= base picture: graded, punch-ins 100 -> 107 % on the face (scale anchored top-left -> offsets) =================
  {
    const kf = (arr) => arr.map(([at, value]) => ({ at, value, easing: "linear" }));
    p.compose([media({ file: v, x: 0, y: 0, width: W, height: H, fit: "fill", trimStart: 0, effects: [grade(0.03)],
      animate: [{ property: "scale", keyframes: kf(D.pz.scale) }, { property: "offsetX", keyframes: kf(D.pz.x) }, { property: "offsetY", keyframes: kf(D.pz.y) }] })],
    { at: 0, dur: DUR, name: "base" });
  }
  // composes are queued and issued sorted by start: Higgsedit's lane planner (assignLane) is greedy in call order
  const Q = [];
  const put = (name, at, end, nodes) => Q.push([nodes, { at: S(at), dur: S(end) - S(at), name }]);

  // ================= 1 · browser impots.gouv.fr (URL typed) — recedes when the OnlyFans tile pops =================
  const IMP = { img: img.impots, iw: 2880, ih: 1800, sx: 0.41, ox: -57, oy: 0 };          // css x 70.. at 0.82 px/css px
  {
    const at = S(T.impots - A), end = S(D.WIN[0][1]);
    put("1 browser impots", at, end, [winShell({ x: 130, y: 790, w: 820, h: 520, duration: end - at, recede: T.onlyfans1 - A - at },
      window_({ url: "impots.gouv.fr", tab: "impots.gouv.fr", typeAt: 0.3, content: IMP }))]);
  }
  // ================= 2 · OnlyFans logo tile =================
  { const at = S(T.onlyfans1 - A), end = S(5.6);
    put("2 logo OnlyFans", at, end, [tile({ x: 460, y: 900, at: 0, duration: end - at, img: img.onlyfans, iw: 96, ih: 96, label: "OnlyFans" })]); }

  // ================= 4 · glass stat card « Au début : quelques centaines d'€ » =================
  { const at = S(T.debut - A), end = S(T.n5 - A + 0.08), x = 140, y = 800, w = 800, h = 420;
    put("4 stat au début", at, end, [el({ x, y, w, h, at: 0, duration: end - at }, [...glass(x, y, w, h, at),
      icon("coins", { x: 48, y: 44, size: 64, color: C.acc, strokeWidth: 2 }), T_("Au début", { size: 44, face: "I600", x: 132, y: 52, color: "#FFFFFFCC" }),
      T_("quelques centaines d'€", { size: 64, x: 48, y: 150, color: C.white }),
      rect({ x: 48, y: 330, width: 704, height: 36, radius: 18, fill: "#FFFFFF26" }),
      rect({ x: 48, y: 330, width: 704, height: 36, radius: 18, fill: C.acc, mask: { shape: "rectangle", x: 0, y: -2, width: 1, height: 40 },
        animate: [{ property: "maskWidth", keyframes: K([0, 1, "hold"], [T.centaines - A - at, 1, EASE], [T.centaines - A - at + 0.5, 2 * 40]) }] })])]); }
  // ================= 5 · same card, bars + counter 5 000 -> 10 000 -> 20 000 € / mois =================
  { const at = S(T.n5 - A), end = S(T.premiere - A + 0.1), x = 140, y = 800, w = 800, h = 420, L = (t) => Math.max(0, t - at);
    const bars = [[T.n5, 70], [T.n10, 140], [T.n20, 250]].map(([t, bh], i) => rect({ x: 560 + i * 66, y: 360 - bh, width: 48, height: bh, radius: 10, fill: i === 2 ? C.acc : "#FFC83D99",
      animate: [{ property: "scaleY", keyframes: K(...(L(t - A) > 0.001 ? [[0, 0.001, "hold"]] : []), [Math.max(0, L(t - A)), 0.001, EASE], [L(t - A) + 0.35, 1]) },
        { property: "offsetY", keyframes: K(...(L(t - A) > 0.001 ? [[0, bh, "hold"]] : []), [Math.max(0, L(t - A)), bh, EASE], [L(t - A) + 0.35, 0]) }] }));
    const step = (t0, t1, from, to, final) => frame({ x: 48, y: 120, width: 520, height: 170, layout: "none", at: L(t0 - A), duration: (t1 === null ? end - at : L(t1 - A)) - L(t0 - A),
      animate: [{ property: "opacity", keyframes: K([0, 0, EASE], [0.06, 1]) }] }, [counter({ x: 0, y: 0, size: 132, final, from, to, suffix: " 000", start: 0, roll: 0.3 })]);
    put("5 stat 20 000", at, end, [el({ x, y, w, h, at: 0, duration: end - at, from: 1 }, [...glass(x, y, w, h, at),
      icon("trending-up", { x: 48, y: 44, size: 64, color: C.acc, strokeWidth: 2 }), T_("Puis…", { size: 44, face: "I600", x: 132, y: 52, color: "#FFFFFFCC" }),
      step(T.n5, T.n10, 0, 5, "5 000"), step(T.n10, T.n20, 5, 10, "10 000"), step(T.n20, null, 10, 20, "20 000"),
      T_("€ / mois", { size: 52, x: 52, y: 300, color: C.acc, at: L(T.n20 - A) + 0.2, animate: [{ property: "opacity", keyframes: K([0, 0, EASE], [0.15, 1]) }] }),
      ...bars, ring(685, 230, 120, L(T.n20) , C.acc)])]); }

  // ================= 6 / 11 · chapter pill (1/2, then 2/2) =================
  const chapter = (n, at, end) => put(`chapter ${n}/2`, at, end, [el({ x: 50, y: 690, w: 230, h: 70, at: 0, duration: end - at, from: 0.8 }, [
    rect({ x: 0, y: 0, width: 230, height: 70, radius: 35, fill: C.pill, shadow: SHADOW }),
    T_(`${n} / 2`, { size: 34, x: 26, y: 13, color: C.acc }),
    ...[0, 1].map((i) => rect({ x: 150 + i * 30, y: 27, width: 16, height: 16, radius: 8, fill: i < n ? C.acc : "#FFFFFF4D" }))])]);
  chapter(1, T.premiere - A, T.ru + 0.4);
  chapter(2, T.deuxieme - A, T.pro + 0.4);

  // ================= 7 / 8 · flux OnlyFans -> Royaume-Uni -> France, coche on « déclares » =================
  { const at = S(T.onlyfans2 - A), end = S(T.declares + 1.2), L = (t) => Math.max(0, t - at), TY = 900;
    const conn = (x1, x2, t) => [path({ x: x1, y: TY + 76, width: x2 - x1, height: 8, d: `M 2 4 L ${x2 - x1 - 2} 4`, stroke: { width: 5, color: "#FFFFFFB3", cap: "round" }, dash: [12, 10],
      ...(() => { const d = drawX(x2 - x1, 8, L(t), 0.3); return { mask: d.mask, animate: [d.anim] }; })() }),
      ...flowDots(x1 + 6, TY + 80, x2 - 6, TY + 80, L(t) + 0.3, end - t - 0.5)];
    put("7 flux", at, end, [frame({ x: 0, y: 0, width: W, height: H, layout: "none", animate: [shake(L(T.mais), 3)] }, [
      tile({ x: 100, y: TY, at: 0, duration: end - at, img: img.onlyfans, iw: 96, ih: 96, label: "OnlyFans" }),
      ...conn(272, 448, T.ru - A + 0.05),
      tile({ x: 460, y: TY, at: L(T.ru - A), duration: end - T.ru + A, img: img.uk, iw: 120, ih: 72, round: 8, label: "Royaume-Uni" }),
      ...conn(632, 808, T.france - A + 0.05),
      tile({ x: 820, y: TY, at: L(T.france - A), duration: end - T.france + A, img: img.fr, iw: 108, ih: 72, round: 8, label: "France" }),
      frame({ x: 940, y: TY - 26, width: 64, height: 64, layout: "none", at: L(T.declares - A), duration: end - T.declares + A }, check(0, 0, 0.001)),
    ])]); }

  // ================= 9 · « Discret ? » crossed out on « non » =================
  { const at = S(T.discret - A), end = S(T.tracable - A + 0.05), L = (t) => Math.max(0, t - at);
    put("9 discret", at, end, [el({ x: 270, y: 880, w: 540, h: 160, at: 0, duration: end - at, animate: [shake(L(T.non), 3)] }, [card(540, 160),
      icon("eye-off", { x: 44, y: 40, size: 80, color: C.ink, strokeWidth: 2 }), T_("Discret ?", { size: 64, x: 150, y: 38, color: C.ink }),
      ...cross(140, 26, 360, 108, L(T.non - A))])]); }
  // ================= 10 · « Traçable » icon tile =================
  { const at = S(T.tracable - A), end = S(T.deuxieme - A + 0.6);
    put("10 traçable", at, end, [tile({ x: 460, y: 880, at: 0, duration: end - at, icon: "scan-search", label: "Traçable" })]); }

  // ================= 12 · browser impots.gouv.fr again: highlighter + zoom 130 % on « Professionnel » =================
  { const at = S(T.fisc - A), end = S(D.WIN[1][1]), L = (t) => Math.max(0, t - at);
    const hl = { x: 186, y: 112, w: 86, h: 30, at: L(T.pro - A) };
    put("12 browser fisc", at, end, [el({ x: 130, y: 790, w: 820, h: 520, at: 0, duration: end - at },
      window_({ url: "impots.gouv.fr", tab: "impots.gouv.fr", typeAt: 0.25, content: { ...IMP, hl, zoom: { at: L(T.pro - A) + 0.1, k: 1.3, ax: hl.x + hl.w / 2, ay: hl.y + hl.h / 2 } } }))]); }

  // ================= 13 · checklist « Activité déclarée » ✓ · « Vrai statut » ✓ =================
  { const at = S(T.declare - A), end = S(T.mal2 - A + 0.05), L = (t) => Math.max(0, t - at), x = 170, y = 860, w = 740, h = 270;
    const row = (yy, t, s) => frame({ x: 0, y: yy, width: w, height: 100, layout: "none", at: L(t - A), animate: [{ property: "opacity", keyframes: K([0, 0, EASE], [0.15, 1]) },
      { property: "offsetX", keyframes: K([0, 30, EASE], [0.3, 0]) }] }, [...check(40, 18, 0.1), T_(s, { size: 50, x: 130, y: 16, color: C.white })]);
    put("13 checklist statut", at, end, [el({ x, y, w, h, at: 0, duration: end - at }, [...glass(x, y, w, h, at), row(30, T.declare, "Activité déclarée"), row(140, T.statut, "Un vrai statut")])]); }

  // ================= 15 · « Impôt sur le revenu » (shake on « c'est », greys when the cotisations arrive) =================
  { const at = S(T.impot - A), end = S(T.cotis - A + 0.25), L = (t) => Math.max(0, t - at);
    put("15 impôt sur le revenu", at, end, [el({ x: 180, y: 880, w: 720, h: 160, at: 0, duration: end - at, animate: [shake(L(T.cest), 3)] }, [card(720, 160),
      icon("landmark", { x: 44, y: 40, size: 80, color: C.ink, strokeWidth: 2 }), T_("Impôt sur le revenu", { size: 52, x: 150, y: 46, color: C.ink }),
      rect({ x: 0, y: 0, width: 720, height: 160, radius: 20, fill: "#8E8E93", at: L(T.cotis - A), animate: [{ property: "opacity", keyframes: K([0, 0, EASE], [0.2, 0.55]) }] })])]); }
  // ================= 16 · URSSAF window (real capture) + callout « Cotisations sociales » =================
  { const at = S(T.cotis - A), end = S(D.WIN[2][1]), L = (t) => Math.max(0, t - at);
    const US = { img: img.urssaf, iw: 2880, ih: 1800, sx: 0.41, ox: -82, oy: 0 };
    const co = "Cotisations sociales", cw = tw(co, 44) + 48;
    const lineD = drawX(150, 150, 0.3, 0.3);
    put("16 urssaf", at, end, [el({ x: 130, y: 790, w: 820, h: 520, at: 0, duration: end - at }, window_({ title: "urssaf.fr", content: US })),
      frame({ x: 0, y: 0, width: W, height: H, layout: "none", at: at + 0.15, duration: end - at - 0.15, animate: [io(end - at - 0.15, 0.1, 0.2)] }, [
        path({ x: 950 - cw - 150, y: 1010, width: 150, height: 150, d: "M 148 148 Q 60 140 8 6", stroke: { width: 6, color: C.acc, cap: "round" }, mask: lineD.mask, animate: [lineD.anim] }),
        frame({ x: 950 - cw, y: 1150, width: cw, height: 84, layout: "none", origin: "center", motion: { enter: { from: { scale: 0.8 }, duration: 0.5, easing: SPRING } } },
          [rect({ x: 0, y: 0, width: cw, height: 84, radius: 20, fill: C.acc, shadow: SHADOW }), T_(co, { size: 44, x: 24, y: 14, color: C.black })])])]); }

  // ================= 17 · gauge « Ce que tu gagnes » drains on « disparaître », counter ≈ 50 % on « moitié » =================
  { const at = S(T.dispa - A), end = S(T.unan - A + 0.1), L = (t) => Math.max(0, t - at), x = 140, y = 800, w = 800, h = 420;
    put("17 jauge moitié", at, end, [el({ x, y, w, h, at: 0, duration: end - at }, [...glass(x, y, w, h, at),
      icon("wallet", { x: 48, y: 44, size: 60, color: C.acc, strokeWidth: 2 }), T_("Ce que tu gagnes", { size: 44, face: "I600", x: 128, y: 50, color: "#FFFFFFCC" }),
      rect({ x: 48, y: 140, width: 704, height: 44, radius: 22, fill: "#FFFFFF26" }),
      rect({ x: 48, y: 140, width: 704, height: 44, radius: 22, fill: C.acc, animate: [{ property: "scaleX", keyframes: K([0, 1, "hold"], [0.15, 1, EASE], [0.95, 0.5]) }] }),
      counter({ x: 48, y: 200, size: 170, w: tw("≈ 100 %", 170) + 20, final: "≈ 50 %", from: 100, to: 50, prefix: "≈ ", suffix: " %", start: L(T.moitie1 - A), roll: 0.5, at: 0 }),
      ring(560, 290, 110, L(T.moitie1), C.acc)])]); }
  // ================= 18 · « +1 an » calendar card =================
  { const at = S(T.unan - A), end = S(T.reclame - A + 0.7), L = (t) => Math.max(0, t - at);
    put("18 un an", at, end, [el({ x: 90, y: 860, w: 400, h: 150, at: 0, duration: end - at }, [card(400, 150),
      icon("calendar", { x: 36, y: 39, size: 72, color: C.acc2, strokeWidth: 2 }),
      counter({ x: 130, y: 30, size: 72, final: "+1 an", from: 0, to: 1, prefix: "+", suffix: " an", start: 0.1, roll: 0.4, color: C.ink })])]); }
  // ================= 19 · iPhone (urssaf.fr mobile, real) + generic notification « Cotisations sociales » =================
  { const at = S(D.PHONE[0][0]), end = S(D.PHONE[0][1]), s = 0.95, PW = Math.round(390 * s), PH = Math.round(844 * s), bz = Math.round(12 * s), SW = PW - 2 * bz, SH = PH - 2 * bz;
    put("19 iphone", at, end, [el({ x: 680, y: 690, w: PW, h: PH, at: 0, duration: end - at, from: 1, fromY: 420, fromRot: 3, blur: true }, [
      rect({ x: 0, y: 0, width: PW, height: PH, radius: Math.round(55 * s), fill: "#111113", shadow: SHADOW }),
      frame({ x: bz, y: bz, width: SW, height: SH, layout: "none", clip: true, radius: Math.round(44 * s) }, [
        rect({ x: 0, y: 0, width: SW, height: SH, fill: C.white }),
        media({ file: img.urssaf_iphone, x: 0, y: 0, width: SW, height: Math.round(SW * 2556 / 1179), fit: "fill" }),
        media({ file: notif, x: (SW - 330) / 2, y: 52, width: 330, height: 100, fit: "fill", at: 0.35, duration: Math.min(2.78, end - at - 0.36), trimStart: 0 })]),
      rect({ x: (PW - 112) / 2, y: bz + 10, width: 112, height: 32, radius: 16, fill: "#000000" })])]); }

  // ================= 21 · « Fraude » crossed out =================
  { const at = S(T.fraude - A), end = S(T.moitie2 - A + 0.05), L = (t) => Math.max(0, t - at);
    put("21 fraude", at, end, [el({ x: 290, y: 880, w: 500, h: 160, at: 0, duration: end - at, animate: [shake(L(T.fraude) + 0.3, 3)] }, [card(500, 160),
      icon("shield-alert", { x: 44, y: 40, size: 80, color: C.ink, strokeWidth: 2 }), T_("Fraude", { size: 64, x: 150, y: 38, color: C.ink }),
      ...cross(140, 26, 320, 108, L(T.fraude) + 0.05)])]); }
  // ================= 22 · pie: half detaches « 50 % · jamais à elles » =================
  { const at = S(T.moitie2 - A), end = S(D.BROLL[0] + 0.05), L = (t) => Math.max(0, t - at), x = 140, y = 800, w = 800, h = 420, R = 130, k = 0.5523 * R;
    const left = `M ${R} 0 C ${R - k} 0 0 ${R - k} 0 ${R} C 0 ${R + k} ${R - k} ${2 * R} ${R} ${2 * R} Z`;
    const right = `M 0 0 C ${k} 0 ${R} ${R - k} ${R} ${R} C ${R} ${R + k} ${k} ${2 * R} 0 ${2 * R} Z`;
    const go = L(T.moitie2) + 0.1;
    put("22 la moitié", at, end, [el({ x, y, w, h, at: 0, duration: end - at }, [...glass(x, y, w, h, at),
      path({ x: 60, y: 80, width: R, height: 2 * R, d: left, fill: C.white }),
      path({ x: 60 + R, y: 80, width: R, height: 2 * R, d: right, fill: C.acc2,
        animate: [{ property: "offsetX", keyframes: K([0, 0, "hold"], [go, 0, EASE], [go + 0.45, 60]) }, { property: "rotation", keyframes: K([0, 0, "hold"], [go, 0, EASE], [go + 0.45, 12]) },
          { property: "opacity", keyframes: K([0, 1, "hold"], [go + 0.3, 1, EASE], [go + 0.6, 0.45]) }] }),
      counter({ x: 400, y: 96, size: 130, final: "50 %", from: 0, to: 50, suffix: " %", start: L(T.moitie2 - A), roll: 0.5, color: C.acc2 }),
      T_("jamais à elles", { size: 48, face: "I600", x: 404, y: 270, color: C.white, at: go, animate: [{ property: "opacity", keyframes: K([0, 0, EASE], [0.2, 1]) }] })])]); }

  // ================= 23 · B-roll cutaway 1.8 s (zoom-whip in / out, 5 frames) =================
  { const [at, end] = D.BROLL.map(S), dur = end - at, f5 = 5 / FPS, Z = 1.25;
    const zk = (a, b) => K([0, a, EASE], [f5, b, "hold"], [dur - f5 - 0.001, b, EASE], [dur - 0.001, a]);
    put("23 b-roll", at, end, [media({ file: broll, x: 0, y: 0, width: W, height: H, fit: "fill", trimStart: 0.2, effects: [grade(0.03)], motionBlur: { samples: 6, shutter: 0.6 },
      animate: [{ property: "scale", keyframes: zk(Z, 1) }, { property: "offsetX", keyframes: zk(-(Z - 1) * W / 2, 0) }, { property: "offsetY", keyframes: zk(-(Z - 1) * H / 2, 0) },
        { property: "opacity", keyframes: K([0, 0, "linear"], [f5 * 0.6, 1, "hold"], [dur - f5 * 0.6 - 0.001, 1, "linear"], [dur - 0.001, 0]) },
        { property: "blur", keyframes: K([0, 18, EASE], [f5, 0, "hold"], [dur - f5 - 0.001, 0, EASE], [dur - 0.001, 18]) }] })]); }

  // ================= 24 · checklist « Structure propre » ✓ « Discrète » ✓ « En règle » ✓ + 100 % =================
  { const at = S(T.structurer - A), end = S(T.comment - A), L = (t) => Math.max(0, t - at), x = 140, y = 800, w = 800, h = 420;
    const row = (yy, t, s, extra = []) => frame({ x: 0, y: yy, width: w, height: 110, layout: "none", at: L(t - A), animate: [{ property: "opacity", keyframes: K([0, 0, EASE], [0.15, 1]) },
      { property: "offsetX", keyframes: K([0, 30, EASE], [0.3, 0]) }] }, [...check(44, 22, 0.1), T_(s, { size: 50, x: 134, y: 24, color: C.white }), ...extra]);
    put("24 checklist structurer", at, end, [el({ x, y, w, h, at: 0, duration: end - at }, [...glass(x, y, w, h, at),
      row(30, T.structurer, "Structure propre"), row(150, T.discrete, "Discrète"),
      row(270, T.cent, "En règle", [counter({ x: 420, y: 18, size: 64, final: "100 %", from: 0, to: 100, suffix: " %", start: 0.05, roll: 0.5, color: C.acc })])])]); }

  // ================= 25 · CTA « Commande ton diagnostic » + lien en bio =================
  { const at = S(T.comment - A), end = S(DUR), L = (t) => Math.max(0, t - at), s1 = "Commande ton diagnostic", w1 = tw(s1, 50) + 56, s2 = "lien en bio", w2 = tw(s2, 34, "I600") + 110;
    put("25 cta", at, end, [el({ x: (W - w1) / 2, y: 900, w: w1, h: 230, at: 0, duration: end - at }, [
      rect({ x: 0, y: 0, width: w1, height: 100, radius: 20, fill: C.acc, shadow: SHADOW }), T_(s1, { size: 50, x: 28, y: 18, color: C.black }),
      frame({ x: (w1 - w2) / 2, y: 130, width: w2, height: 76, layout: "none", at: 0.2, animate: [{ property: "opacity", keyframes: K([0, 0, EASE], [0.15, 1]) }] }, [
        rect({ x: 0, y: 0, width: w2, height: 76, radius: 38, fill: C.pill }), icon("arrow-down", { x: 26, y: 18, size: 40, color: C.acc, strokeWidth: 2.5 }),
        T_(s2, { size: 34, face: "I600", x: 80, y: 16, color: C.white })]),
      ring(w1 / 2, 50, 260, Math.max(0.01, L(T.commande - A)), C.acc)])]); }

  Q.sort((a, b) => a[1].at - b[1].at).forEach(([nodes, o]) => p.compose(nodes, o));

  // ================= captions (one overlay, last = top lane): karaoke, keyword pop, number roll, shake on oppositions =================
  const CAPS = [];
  for (const c of D.caps) {
    const box = c.mode === "phone" ? { x: 40, w: 620, cy: 1300 } : c.mode === "win" ? { x: 60, w: 960, cy: 1420 } : { x: 60, w: 960, cy: 1300 };
    const gap = 16, LH = 92, total = c.w.reduce((s, w) => s + w.w, 0) + gap * (c.w.length - 1), lines = total > box.w ? 2 : 1, hh = LH * lines;
    const dur = S(c.at + c.dur) - S(c.at);
    const words = c.w.map((w) => {
      const end = Math.min(w.off, dur - 0.002);
      const keys = [];
      if (w.on > 0.001) keys.push({ at: 0, value: C.white, easing: "hold" });
      keys.push({ at: Math.max(0, w.on), value: C.acc, easing: "hold" });
      if (end < dur - 0.02 && !w.key) keys.push({ at: end, value: C.white, easing: "hold" });
      if (keys.length < 2) keys.push({ at: dur - 0.001, value: keys[keys.length - 1].value });
      const on = Math.max(0.0005, w.on);
      const sk = w.key
        ? K([0, 1, "hold"], [on, 1, EASE], [on + 0.07, 1.25, EASE], [on + 0.25, 1.06, "hold"], ...(end - 0.1 > on + 0.25 ? [[end - 0.1, 1.06, EASE], [end, 1]] : []))
        : K([0, 1, "hold"], [on, 1, EASE], [on + 0.08, 1.06, "hold"], ...(end - 0.08 > on + 0.08 ? [[end - 0.08, 1.06, EASE], [end, 1]] : []));
      const shared = { x: 0, y: 0, width: w.w, height: LH, align: "center", fontFamily: MONT, fontWeight: 800, fontSize: 68, strokeColor: "#000000CC", strokeWidth: 5,
        shadow: { x: 0, y: 4, blur: 14, color: "#00000080" } };
      const inner = w.num
        ? [frame({ x: 0, y: 0, width: w.w, height: LH, layout: "none", motion: { timeline: { at: on, duration: Math.min(0.5, dur - on - 0.02), easing: EASE, targets: [{ target: `cap${cid}`, counter: { from: 0, to: w.num[0], decimals: 0, suffix: w.num[1] } }] } } },
            [frame({ name: `cap${cid++}`, x: 0, y: 0, width: w.w, height: LH, layout: "none" }, [text(w.t, { ...shared, color: C.acc })])])]
        : [text(w.t, { ...shared, color: C.white, animate: [{ property: "color", keyframes: keys }] })];
      const skf = sk.filter((k, i, a) => (i === 0 || k.at > a[i - 1].at) && k.at < dur - 0.001);
      return frame({ width: w.w, height: LH, layout: "none", origin: "center", animate: [...(skf.length >= 2 ? [{ property: "scale", keyframes: skf }] : []),
        ...(w.num ? [{ property: "opacity", keyframes: K([0, 0, "hold"], [on, 0, "linear"], [on + 0.03, 1]) }] : [])] }, inner);
    });
    const sh = c.w.filter((w) => w.shake).map((w) => w.on);
    CAPS.push(frame({ x: box.x, y: box.cy - hh / 2, width: box.w, height: hh, layout: "row", wrap: true, gap, rowGap: 0, justify: "center", align: "center", at: S(c.at), duration: dur,
      animate: [{ property: "opacity", keyframes: K([0, 0, EASE], [0.15, 1, "hold"], [Math.max(0.16, dur - 0.1), 1, "linear"], [dur, 0]) },
        { property: "blur", keyframes: K([0, 10, EASE], [0.15, 0]) }, ...(sh.length ? [shake(Math.max(0.001, sh[0]), 3)] : [])] }, words));
  }
  p.compose(frame({ x: 0, y: 0, width: W, height: H, layout: "none" }, CAPS), { at: 0, dur: DUR, name: "captions" });

  const mode = process.env.REEL_MODE || "frames";
  if (mode === "frames") {
    const only = process.env.REEL_TIMES ? process.env.REEL_TIMES.split(",").map(Number) : [];
    for (const t of only) await p.frame(t, `renders/f_${t.toFixed(2)}.png`);
  } else if (mode === "draft") {
    await p.render("renders/draft.mp4", { draft: true, concurrency: 3 });
  } else if (mode === "master") {
    await p.render("renders/master.mp4", { depth: 8, bitrate: 12_000_000, concurrency: 3 });
  }
};
