// Reel 2 « Holding : régime mère-fille » — split-screen, Higgsedit v0.14 (f39e3bc5882b), 1080x1920 @ 30 fps.
// Generated by gen_edit.py (captions + Zone A keys). Every time is on the jump-cut timeline of media/cut.mp4.
// Layout: Zone A face y 0–760 · separator 760 · captions 800–900 · stage 940–1540 (x 72–1008) · dead zone 1570–1920.
import { createRequire } from "node:module";

const D = /*__DATA__*/null;
const W = 1080, H = 1920, FONT = "Montserrat";
const C = { bg: "#FFFFFF", fg: "#111111", acc: "#0B6E4F", acc2: "#D1453B", grey: "#8A918E", line: "#E4E7E5", soft: "#F3F6F4", accSoft: "#E3F1EA", acc2Soft: "#FBE9E7" };
const EASE = [0.2, 0.8, 0.2, 1];                        // the one curve of this reel
const EXPO = [0.16, 1, 0.3, 1];                         // counters only (expo-out, per brief)
const SPRING = { kind: "spring", stiffness: 300, damping: 22 };
const MEDIA = "/home/user/w2";
const ST = { x: 72, y: 940, w: 936, h: 600 };           // stage
const CLIP_Y = 930;                                      // stage clip frame top (screen y)
const y = (sy) => sy - CLIP_Y;                           // screen y -> stage-clip local y

// Measure with the exact faces the renderer uses (800 / 600 registered in the project).
const require = createRequire("/opt/fable/package.json");
const { GlobalFonts, createCanvas } = require("@napi-rs/canvas");
GlobalFonts.registerFromPath(`${MEDIA}/reel/fonts/montserrat-800.woff2`, "M800");
GlobalFonts.registerFromPath(`${MEDIA}/reel/fonts/montserrat-600.woff2`, "M600");
const ctx = createCanvas(4, 4).getContext("2d");
const tw = (s, size, wt = 800) => { ctx.font = `${size}px ${wt === 800 ? "M800" : "M600"}`; return Math.ceil(ctx.measureText(s).width * 1.06) + 10; };

const GRAIN = `vec4 pixel(vec2 uv){
  vec4 c = texture(u_src, uv);
  float n = fract(sin(dot(floor(uv * u_resolution) + floor(u_time * 30.0) * 17.0, vec2(12.9898, 78.233))) * 43758.5453) - 0.5;
  vec3 g = c.rgb;
  float l = dot(g, vec3(0.2126, 0.7152, 0.0722));
  g = mix(vec3(l), g, u_sat);
  g = (g - 0.5) * u_con + 0.5;
  return vec4(clamp(g + n * u_amt, 0.0, 1.0) * c.a, c.a);
}`;
const grain = (amt, con = 1, sat = 1) => ({ kind: "shader", params: { glsl: GRAIN, amt, con, sat } });

// ---------- small builders ----------
const clean = (o) => Object.fromEntries(Object.entries(o).filter(([, v]) => v !== undefined));
const K = (...pairs) => pairs.map(([at, value, easing]) => ({ at, value, ...(easing ? { easing } : {}) }));
const fadeIn = (at = 0, d = 0.15) => ({ property: "opacity", keyframes: at > 0 ? K([0, 0, "hold"], [at, 0, EASE], [at + d, 1]) : K([0, 0, EASE], [d, 1]) });
// stroke reveal from the path origin (mask centred on the origin, grows to twice the length)
// (the 2 px seed sits 6 px before the origin, so nothing shows before the stroke starts; round caps included)
const drawX = (w, h, at, dur) => ({ mask: { shape: "rectangle", x: -8, y: -6, width: 2, height: h + 12 },
  anim: { property: "maskWidth", keyframes: K([0, 2, "hold"], [Math.max(at, 0.001), 2, EASE], [at + dur, 2 * w + 24]) } });
const drawY = (w, h, at, dur, up = false) => ({ mask: { shape: "rectangle", x: -6, y: up ? h + 6 : -8, width: w + 12, height: 2 },
  anim: { property: "maskHeight", keyframes: K([0, 2, "hold"], [Math.max(at, 0.001), 2, EASE], [at + dur, 2 * h + 24]) } });
const circleD = (r, p = 0) => { const k = 0.5523 * r, c = r + p;
  return `M ${c + r} ${c} C ${c + r} ${c + k} ${c + k} ${c + r} ${c} ${c + r} C ${c - k} ${c + r} ${c - r} ${c + k} ${c - r} ${c} C ${c - r} ${c - k} ${c - k} ${c - r} ${c} ${c - r} C ${c + k} ${c - r} ${c + r} ${c - k} ${c + r} ${c} Z`; };

export default async ({ project, text, rect, media, path, frame, icon }) => {
  const p = await project({ dir: "reel", size: `${W}x${H}`, fps: 30, background: C.bg });
  const v = await p.add(`${MEDIA}/cut.mp4`);
  const TOTAL = D.DUR + D.END;

  const label = (s, o = {}) => {
    const size = o.size || 44, wt = o.weight || 800, w = o.width || tw(s, size, wt);
    return text(s, { x: o.x ?? 0, y: o.y ?? 0, width: w, height: Math.round(size * 1.3), align: o.align || "left", fontFamily: FONT,
      fontWeight: wt, fontSize: size, color: o.color || C.fg, ...(o.at !== undefined ? { at: o.at } : {}), ...(o.duration ? { duration: o.duration } : {}),
      ...(o.animate ? { animate: o.animate } : {}), ...(o.motion ? { motion: o.motion } : {}) });
  };
  // pop-in (spring on scale, opacity on its own track) for any frame
  const pop = (o, kids) => { const { fromScale, fromY, exit, animate, ...rest } = o;
    return frame({ layout: "none", origin: "center", ...rest,
      motion: { enter: { from: { scale: fromScale ?? 0.6, ...(fromY ? { y: fromY } : {}) }, duration: 0.5, easing: SPRING }, ...(exit ? { exit } : {}) },
      animate: [fadeIn(0, 0.12), ...(animate || [])] }, kids); };
  // white card with a hairline border and soft shadow; icon optional
  const card = (s, o = {}) => {
    const size = o.size || 46, wt = o.weight || 800, iw = o.icon ? (o.iconSize || 64) : 0, gap = o.icon ? 18 : 0, tW = tw(s, size, wt);
    const w = o.w || (tW + iw + gap + 72), h = o.h || 116, x0 = (w - (iw + gap + tW)) / 2, th = Math.round(size * 1.3);
    return frame(clean({ name: o.name, x: o.x ?? (W - w) / 2, y: o.y, width: w, height: h, layout: "none", origin: "center", at: o.at, duration: o.duration,
      motion: o.still ? undefined : (o.motion || { enter: { from: { scale: 0.6 }, duration: 0.5, easing: SPRING } }),
      animate: [...((o.animate || []).some((a) => a.property === "opacity") || o.still ? [] : [fadeIn(0, 0.12)]), ...(o.animate || [])] }),
      [rect({ x: 0, y: 0, width: w, height: h, radius: 28, fill: o.bg || "#FFFFFF", strokeColor: o.border || C.line, strokeWidth: 3, shadow: { x: 0, y: 12, blur: 34, color: "#0000001F" } }),
        ...(o.icon ? [icon(o.icon, { x: x0, y: (h - iw) / 2, size: iw, color: o.iconColor || o.color || C.fg, strokeWidth: 2 })] : []),
        text(s, { x: x0 + iw + gap, y: (h - th) / 2 + 2, width: tW, height: th, align: "center", fontFamily: FONT, fontWeight: wt, fontSize: size, color: o.color || C.fg })]);
  };
  // impact: ring + max 8 particles, 0.5 s, centred on (cx, cy) in stage-local coordinates
  const impact = (cx, cy, at, color, r = 120) => {
    const out = [path({ x: cx - r - 6, y: cy - r - 6, width: 2 * r + 12, height: 2 * r + 12, d: circleD(r, 6), stroke: { width: 6, color }, at, duration: 0.55,
      animate: [{ property: "scale", keyframes: K([0, 0.35, EASE], [0.5, 1.25]) }, { property: "opacity", keyframes: K([0, 0.9, EASE], [0.5, 0]) }] })];
    for (let i = 0; i < 8; i++) {
      const a = (i / 8) * Math.PI * 2 + 0.3, d = r * 1.45, s = i % 2 ? 12 : 16;
      out.push(rect({ x: cx - s / 2, y: cy - s / 2, width: s, height: s, radius: s / 2, fill: color, at, duration: 0.55,
        animate: [{ property: "offsetX", keyframes: K([0, 0, EASE], [0.5, Math.cos(a) * d]) }, { property: "offsetY", keyframes: K([0, 0, EASE], [0.5, Math.sin(a) * d]) },
          { property: "opacity", keyframes: K([0, 1, "hold"], [0.2, 1, EASE], [0.52, 0]) }] }));
    }
    return out;
  };
  // looping flow of dots/glyphs from (x1,y1) to (x2,y2), stage-local
  const flow = (x1, y1, x2, y2, at, dur, color, glyph, P = 0.9) => {
    const n = 3, out = [];
    for (let i = 0; i < n; i++) {
      const start = at + (i * P) / n, reps = Math.floor((dur - (start - at)) / (P + 0.001));
      if (reps < 1) continue;
      const node = glyph
        ? { x: x1 - 22, y: y1 - 30, width: 44, height: 60 }
        : { x: x1 - 8, y: y1 - 8, width: 16, height: 16 };
      const anim = [
        { property: "offsetX", keyframes: K([0, 0, "linear"], [P, x2 - x1, "hold"], [P + 0.001, 0]), ...(reps > 1 ? { repeat: reps } : {}) },
        { property: "offsetY", keyframes: K([0, 0, "linear"], [P, y2 - y1, "hold"], [P + 0.001, 0]), ...(reps > 1 ? { repeat: reps } : {}) },
        { property: "opacity", keyframes: K([0, 0, "linear"], [0.15, 1, "hold"], [P - 0.15, 1, "linear"], [P, 0, "hold"], [P + 0.001, 0]), ...(reps > 1 ? { repeat: reps } : {}) },
      ];
      out.push(frame({ x: 0, y: 0, width: W, height: 640, layout: "none", at: start, duration: reps * (P + 0.001) }, [glyph
        ? text(glyph, { ...node, align: "center", fontFamily: FONT, fontWeight: 800, fontSize: 44, color, animate: anim })
        : rect({ ...node, radius: 8, fill: color, animate: anim })]));
    }
    return out;
  };
  // one stage scene: clip frame (stage bounds) > transition frame > 2.5D drift frame > content
  const scene = (name, at, end, kids, o = {}) => {
    const dur = end - at;
    const drift = [{ property: "offsetY", keyframes: K([0, 4, "linear"], [dur - 0.001, -6]) },
      { property: "offsetX", keyframes: K([0, -4, EASE], [dur / 2, 4, EASE], [dur - 0.001, -4]) }];
    p.compose(frame({ x: 0, y: CLIP_Y, width: W, height: 640, layout: "none", clip: true }, [
      frame({ x: 0, y: 0, width: W, height: 640, layout: "none", origin: "center",
        ...(o.enter || o.exit ? { motion: { ...(o.enter ? { enter: o.enter } : {}), ...(o.exit ? { exit: o.exit } : {}) } } : {}),
        ...(o.blur ? { motionBlur: { samples: 6, shutter: 0.6 } } : {}) }, [
        frame({ x: 0, y: 0, width: W, height: 640, layout: "none", origin: "center", animate: drift }, kids)])]),
    { at, dur, name });
  };
  const SWIPE_IN = { from: { x: 760 }, duration: 0.3, easing: EASE };
  const SWIPE_OUT = { to: { x: -760 }, duration: 0.24, easing: EASE };
  const wipe = (t) => p.compose(frame({ x: 0, y: CLIP_Y, width: W, height: 640, layout: "none", clip: true }, [
    rect({ x: -1240, y: 0, width: 1240, height: 640, fill: C.acc, animate: [{ property: "offsetX", keyframes: K([0, 0, "linear"], [0.38, 2400]) }], motionBlur: { samples: 6, shutter: 0.6 } })]),
  { at: t - 0.19, dur: 0.4, name: "wipe" });
  const iris = (t) => p.compose(frame({ x: 0, y: CLIP_Y, width: W, height: 640, layout: "none", clip: true }, [
    path({ x: 540 - 620, y: 320 - 620, width: 1240, height: 1240, d: circleD(620), fill: C.acc,
      animate: [{ property: "scale", keyframes: K([0, 0.02, EASE], [0.18, 1, "hold"], [0.2, 1, EASE], [0.38, 0.02]) }] })]),
  { at: t - 0.18, dur: 0.38, name: "iris" });

  // ================= spine: picture + cleaned voice (audio lives here) =================
  p.cut(v, { from: 0, dur: D.DUR, fit: "cover" });

  // ================= Zone A: face, 154 % crop, face-tracked, punch-ins, grade + light grain =================
  {
    const Z = D.zone, MW = 1080 * Z.S0, MH = 1036 * Z.S0;
    const kf = (arr) => arr.map(([at, value]) => ({ at, value, easing: "linear" }));
    p.compose([
      rect({ x: 0, y: 0, width: W, height: H, fill: C.bg }),
      frame({ x: 0, y: 0, width: W, height: 760, layout: "none", clip: true }, [
        media({ file: v, x: (W - MW) / 2, y: 300 - MH / 2, width: MW, height: MH, fit: "fill", trimStart: 0,
          effects: [grain(0.02, 1.05, 0.95)],
          animate: [{ property: "scale", keyframes: kf(Z.scale) }, { property: "offsetX", keyframes: kf(Z.x) }, { property: "offsetY", keyframes: kf(Z.y) }] })]),
    ], { at: 0, dur: D.DUR, name: "zone A" });
  }

  // ================= Zone B: white paper with grain (≤ 0.03), separator shadow + progress bar =================
  p.compose([
    rect({ x: 0, y: 760, width: W, height: H - 760, fill: C.bg, effects: [grain(0.028)] }),
    rect({ x: 0, y: 760, width: W, height: 24, fill: { kind: "linear", angle: 180, stops: [{ offset: 0, color: "#000000", opacity: 0.16 }, { offset: 1, color: "#000000", opacity: 0 }] } }),
    rect({ x: 0, y: 756, width: W, height: 6, fill: "#0B6E4F26" }),
    rect({ x: 0, y: 756, width: W, height: 6, fill: C.acc, mask: { shape: "rectangle", x: -1, y: -2, width: 2, height: 10 },
      animate: [{ property: "maskWidth", keyframes: K([0, 2, "linear"], [D.DUR - 0.001, 2 * W + 4]) }] }),
  ], { at: 0, dur: D.DUR, name: "zone B + separator" });

  // ================= captions (band y 800–900): karaoke, active word in accent =================
  for (const c of D.caps) {
    const words = c.w.map((w) => {
      const keys = [];
      if (w.on > 0) keys.push({ at: 0, value: C.fg, easing: "hold" });
      keys.push({ at: w.on, value: C.acc, easing: "hold" });
      if (w.off < c.dur - 0.02) keys.push({ at: w.off, value: C.fg, easing: "hold" });
      if (keys.length < 2) keys.push({ at: c.dur - 0.01, value: keys[keys.length - 1].value });
      return text(w.t, { width: tw(w.t, 58), height: 76, align: "center", fontFamily: FONT, fontWeight: 800, fontSize: 58, color: C.fg,
        animate: [{ property: "color", keyframes: keys }] });
    });
    p.compose(frame({ x: 72, y: 812, width: 936, height: 76, layout: "row", gap: 2, justify: "center", align: "center",
      motion: { enter: { from: { opacity: 0, y: 8 }, duration: 0.1 } } }, words), { at: c.at, dur: c.dur, name: "caption" });
  }

  // ================= STAGE (y 940–1540) — 12 scenes, see SCENES.md =================
  const A = 0.15;   // anticipation

  // --- 1 [0 → 4.40] counter 0 → 100 000 € ---
  {
    const t0 = 0, t1 = 4.40, cntAt = 1.66 - A - t0, cw = tw("100 000 €", 150), cx = (W - cw) / 2;
    scene("1 compteur", t0, t1, [
      pop({ x: (W - tw("SANS HOLDING", 34) - 48) / 2, y: y(968), width: tw("SANS HOLDING", 34) + 48, height: 64, background: C.acc2Soft, radius: 32, at: 0.0, duration: t1 - t0 },
        [label("SANS HOLDING", { size: 34, x: 24, y: 10, color: C.acc2 })]),
      label("0 €", { size: 150, x: cx, y: y(1110), width: cw, align: "center", color: "#C9CECB", at: 0.2, duration: cntAt - 0.2 + 0.05, animate: [fadeIn(0, 0.2)] }),
      frame({ x: cx, y: y(1110), width: cw, height: 196, layout: "none", at: cntAt, duration: t1 - cntAt,
        motion: { timeline: { at: 0, duration: 1.2, easing: EXPO, targets: [{ target: "cnt", counter: { from: 0, to: 100, suffix: " 000 €" } }] } },
        animate: [fadeIn(0, 0.08), { property: "offsetY", keyframes: K([0, 18, EASE], [0.3, 0, "hold"], [1.2, 0, EASE], [1.32, -6, EASE], [1.5, 0]) }] },
        [frame({ name: "cnt", x: 0, y: 0, width: cw, height: 196, layout: "none" },
          [text("100 000 €", { x: 0, y: 0, width: cw, height: 196, align: "center", fontFamily: FONT, fontWeight: 800, fontSize: 150, color: C.fg })])]),
      pop({ x: (W - 470) / 2, y: y(1370), width: 470, height: 96, background: C.soft, radius: 48, at: 3.27 - A - t0, duration: t1 - (3.27 - A), fromY: 30, fromScale: 0.8 },
        [icon("wallet", { x: 44, y: 16, size: 64, color: C.fg, strokeWidth: 2 }), label("Compte perso", { size: 40, x: 126, y: 22, weight: 600 })]),
    ], { exit: SWIPE_OUT, blur: true });
  }

  // --- 2 [4.40 → 6.70] flux 100 000 € → Flat tax (morph into the receipt header) ---
  const RX = 190, RW = 700, HEAD = { x: RX + 40, y: 986, w: 620, h: 104 };
  {
    const t0 = 4.40, t1 = 6.70;
    const flatAt = 6.11 - A - t0;
    scene("2 flux flat tax", t0, t1, [
      card("100 000 €", { x: 96, y: y(1180), w: 360, h: 116, size: 50, at: 0, duration: t1 - t0 - 0.05, motion: { enter: { from: { x: 60 }, duration: 0.3, easing: EASE } },
        animate: [{ property: "opacity", keyframes: K([0, 1, "hold"], [t1 - t0 - 0.3, 1, EASE], [t1 - t0 - 0.06, 0]) }] }),
      (() => { const d = drawX(200, 12, 5.38 - t0, 0.5); return path({ x: 470, y: y(1232), width: 200, height: 12, d: "M 2 6 L 198 6", stroke: { width: 5, color: C.grey, cap: "round" }, dash: [14, 12],
        mask: d.mask, animate: [d.anim, { property: "opacity", keyframes: K([0, 1, "hold"], [t1 - t0 - 0.3, 1, EASE], [t1 - t0 - 0.06, 0]) }] }); })(),
      ...flow(470, y(1238), 660, y(1238), 5.62 - t0, t1 - 5.62 - 0.05, C.acc2, null, 0.6),
      // Flat tax card: pops at « flat », then glides into the receipt header position (morph)
      frame({ x: 680, y: y(1174), width: 300, height: 128, layout: "none", at: flatAt, duration: t1 - t0 - flatAt,
        motion: { enter: { from: { scale: 0.6 }, duration: 0.5, easing: SPRING } },
        animate: [fadeIn(0, 0.12),
          { property: "offsetX", keyframes: K([0, 0, "hold"], [t1 - t0 - flatAt - 0.3, 0, EASE], [t1 - t0 - flatAt - 0.001, HEAD.x - 680]) },
          { property: "offsetY", keyframes: K([0, 0, "hold"], [t1 - t0 - flatAt - 0.3, 0, EASE], [t1 - t0 - flatAt - 0.001, HEAD.y - 1174]) }] },
        [rect({ x: 0, y: 0, width: 300, height: 128, radius: 28, fill: C.acc2Soft, strokeColor: C.acc2, strokeWidth: 3 }),
          icon("landmark", { x: 26, y: 30, size: 68, color: C.acc2, strokeWidth: 2 }),
          label("Flat tax", { size: 44, x: 108, y: 35, color: C.acc2 })]),
    ], { enter: SWIPE_IN, blur: true });
  }

  // --- 3+4 [6.70 → 13.30] receipt: 100 000 € · Flat tax 30 % −30 000 € · Il te reste 70 000 € ; then the cross + stamp ---
  {
    const t0 = 6.70, t1 = 13.30, L = (t) => t - t0;
    const row = (yy, a, b, col) => [label(a, { size: 40, weight: 600, x: RX + 44, y: y(yy), color: C.fg }), label(b, { size: 40, x: RX + RW - 44 - tw(b, 40), y: y(yy), width: tw(b, 40), align: "right", color: col })];
    const crossAt = L(12.01 - A), stampAt = L(12.71 - A), taxY = 1236;
    scene("3-4 reçu", t0, t1, [
      rect({ x: RX, y: y(960), width: RW, height: 560, radius: 30, fill: "#FFFFFF", strokeColor: C.line, strokeWidth: 3, shadow: { x: 0, y: 14, blur: 40, color: "#0000001C" }, animate: [fadeIn(0, 0.2)] }),
      // header (= the Flat tax card, same place as the end of the morph)
      frame({ x: HEAD.x, y: y(HEAD.y), width: 300, height: 128, layout: "none" },
        [rect({ x: 0, y: 0, width: 300, height: 128, radius: 28, fill: C.acc2Soft, strokeColor: C.acc2, strokeWidth: 3 }),
          icon("landmark", { x: 26, y: 30, size: 68, color: C.acc2, strokeWidth: 2 }), label("Flat tax", { size: 44, x: 108, y: 35, color: C.acc2 })]),
      frame({ x: 0, y: 0, width: W, height: 640, layout: "none", animate: [fadeIn(0.05, 0.2), { property: "offsetY", keyframes: K([0, 16, EASE], [0.3, 0]) }] },
        row(1150, "Dividendes", "100 000 €", C.fg)),
      // tax row: highlight, then crossed out, greyed, trembling
      rect({ x: RX + 24, y: y(taxY - 14), width: RW - 48, height: 80, radius: 16, fill: C.acc2Soft, at: L(10.43 - A), duration: t1 - (10.43 - A),
        animate: [{ property: "scaleX", keyframes: K([0, 0.2, EASE], [0.3, 1]) }, fadeIn(0, 0.1)] }),
      frame({ x: 0, y: 0, width: W, height: 640, layout: "none", at: L(6.89 - A), duration: t1 - (6.89 - A),
        animate: [{ property: "offsetX", keyframes: K([0, 30, EASE], [0.3, 0, "hold"], [crossAt - L(6.89 - A) + 0.25, 0, "linear"], [crossAt - L(6.89 - A) + 0.3, 2, "linear"], [crossAt - L(6.89 - A) + 0.35, -2, "linear"], [crossAt - L(6.89 - A) + 0.4, 2, "linear"], [crossAt - L(6.89 - A) + 0.45, -2, "linear"], [crossAt - L(6.89 - A) + 0.5, 0]) },
          { property: "opacity", keyframes: K([0, 0, EASE], [0.12, 1, "hold"], [crossAt - L(6.89 - A) + 0.25, 1, EASE], [crossAt - L(6.89 - A) + 0.45, 0.45]) }] },
        [label("Flat tax 30 %", { size: 40, weight: 600, x: RX + 44, y: y(taxY) }), label("−30 000 €", { size: 44, x: RX + RW - 44 - tw("−30 000 €", 44), y: y(taxY - 3), width: tw("−30 000 €", 44), align: "right", color: C.acc2 })]),
      ...impact(RX + 44 + tw("Flat tax 30 %", 40, 600) - 60, y(taxY + 26), L(6.89 - A), C.acc2, 90),
      // red cross over −30 000 € (2 strokes, 0.25 s)
      ...(() => { const cx0 = RX + RW - 44 - tw("−30 000 €", 44) - 6, cw = tw("−30 000 €", 44) + 12, ch = 70;
        const a = drawX(cw, ch, crossAt, 0.14), b = drawX(cw, ch, crossAt + 0.11, 0.14);
        return [path({ x: cx0, y: y(taxY - 12), width: cw, height: ch, d: `M 4 4 L ${cw - 4} ${ch - 4}`, stroke: { width: 8, color: C.acc2, cap: "round" }, mask: a.mask, animate: [a.anim] }),
          path({ x: cx0, y: y(taxY - 12), width: cw, height: ch, d: `M 4 ${ch - 4} L ${cw - 4} 4`, stroke: { width: 8, color: C.acc2, cap: "round" }, mask: b.mask, animate: [b.anim] })]; })(),
      // divider + total
      (() => { const d = drawX(RW - 88, 8, L(7.4), 0.6); return path({ x: RX + 44, y: y(1330), width: RW - 88, height: 8, d: `M 2 4 L ${RW - 90} 4`, stroke: { width: 3, color: C.fg, cap: "round" }, dash: [10, 10], mask: d.mask, animate: [d.anim] }); })(),
      label("Il te reste", { size: 40, weight: 600, x: RX + 44, y: y(1380), at: L(7.49 - A), animate: [fadeIn(0, 0.15), { property: "offsetY", keyframes: K([0, 14, EASE], [0.3, 0]) }] }),
      frame({ x: RX + RW - 44 - tw("70 000 €", 76), y: y(1360), width: tw("70 000 €", 76), height: 100, layout: "none", origin: "center", at: L(8.57 - A),
        motion: { enter: { from: { scale: 1.6 }, duration: 0.5, easing: SPRING } }, animate: [fadeIn(0, 0.08)] },
        [label("70 000 €", { size: 76, x: 0, y: 0, color: C.acc })]),
      // stamp « DÉFINITIVEMENT »
      frame({ x: (W - 640) / 2, y: y(1060), width: 640, height: 120, layout: "none", origin: "center", at: stampAt,
        motion: { enter: { from: { scale: 1.8, rotation: -8 }, to: { rotation: -8 }, duration: 0.45, easing: SPRING } },
        animate: [fadeIn(0, 0.06), { property: "offsetY", keyframes: K([0, 0, "hold"], [0.3, 0, "linear"], [0.34, 3, "linear"], [0.38, -2, "linear"], [0.42, 0]) }] },
        [rect({ x: 0, y: 0, width: 640, height: 120, radius: 14, fill: "#FFFFFFE6", strokeColor: C.acc2, strokeWidth: 7 }),
          label("DÉFINITIVEMENT", { size: 62, x: 0, y: 20, width: 640, align: "center", color: C.acc2 })]),
    ]);
    wipe(13.30);
  }

  // --- 5 [13.30 → 15.50] SCÉNARIO 2 + « Ta holding » (morph up) ---
  const HOLD = { x: (W - 400) / 2, y: 972, w: 400, h: 116 };
  {
    const t0 = 13.30, t1 = 15.50, L = (t) => t - t0, sw = tw("SCÉNARIO 2", 120);
    const hAt = L(14.93 - A), up = t1 - t0 - hAt;
    scene("5 scénario 2", t0, t1, [
      frame({ x: (W - sw) / 2, y: y(1010), width: sw, height: 160, layout: "none", origin: "center", at: 0.1,
        motion: { enter: { from: { scale: 1.4 }, duration: 0.3, easing: EASE } },
        animate: [{ property: "blur", keyframes: K([0, 12, EASE], [0.25, 0]) },
          { property: "opacity", keyframes: K([0, 0, EASE], [0.12, 1, "hold"], [t1 - t0 - 0.1 - 0.35, 1, EASE], [t1 - t0 - 0.1 - 0.05, 0]) }] },
        [label("SCÉNARIO 2", { size: 120, x: 0, y: 0, width: sw, align: "center" })]),
      (() => { const d = drawX(sw * 0.6, 20, L(13.7), 0.5); return path({ x: (W - sw * 0.6) / 2, y: y(1170), width: sw * 0.6, height: 20, d: `M 2 12 Q ${sw * 0.3} 2 ${sw * 0.6 - 2} 10`, stroke: { width: 9, color: C.acc, cap: "round" }, mask: d.mask,
        animate: [d.anim, { property: "opacity", keyframes: K([0, 1, "hold"], [t1 - t0 - 0.45, 1, EASE], [t1 - t0 - 0.1, 0]) }] }); })(),
      card("Ta holding", { name: "hold", x: HOLD.x, y: y(1300), w: HOLD.w, h: HOLD.h, icon: "building-2", iconColor: C.acc, size: 46, at: hAt, duration: up,
        animate: [{ property: "offsetY", keyframes: K([0, 0, "hold"], [up - 0.32, 0, EASE], [up - 0.001, HOLD.y - 1300]) }] }),
    ]);
  }

  // --- 6 [15.50 → 20.00] Holding → détient → Ta société ; badge ≥ 2 ans ---
  {
    const t0 = 15.50, t1 = 20.00, L = (t) => t - t0;
    const arrowAt = L(16.65 - A), socAt = L(17.65 - A), badgeAt = L(19.37 - A);
    const d = drawY(60, 190, arrowAt, 0.8);
    scene("6 schéma détient", t0, t1, [
      card("Ta holding", { x: HOLD.x, y: y(HOLD.y), w: HOLD.w, h: HOLD.h, icon: "building-2", iconColor: C.acc, size: 46, still: true }),
      path({ x: 510, y: y(1100), width: 60, height: 190, d: "M 30 2 C 22 60 40 120 30 186", stroke: { width: 7, color: C.acc, cap: "round" }, mask: d.mask, animate: [d.anim] }),
      path({ x: 506, y: y(1256), width: 68, height: 44, d: "M 6 6 L 34 36 L 62 6", stroke: { width: 7, color: C.acc, cap: "round" }, at: arrowAt + 0.7, animate: [fadeIn(0, 0.1)] }),
      label("détient", { size: 40, weight: 600, x: 590, y: y(1168), color: C.acc, at: arrowAt + 0.2, animate: [fadeIn(0, 0.2), { property: "offsetX", keyframes: K([0, -16, EASE], [0.3, 0]) }] }),
      card("Ta société", { x: (W - 420) / 2, y: y(1310), w: 420, h: 116, icon: "briefcase", size: 46, at: socAt }),
      pop({ x: 96, y: y(1150), width: 290, height: 92, background: C.accSoft, radius: 46, at: badgeAt, duration: t1 - t0 - badgeAt },
        [icon("calendar", { x: 30, y: 18, size: 56, color: C.acc, strokeWidth: 2 }), label("≥ 2 ans", { size: 44, x: 102, y: 20, color: C.acc })]),
    ], { exit: { to: { y: -24, opacity: 0 }, duration: 0.22, easing: EASE } });
  }

  // --- 7 [20.00 → 23.80] checklist of the two conditions ---
  {
    const t0 = 20.00, t1 = 23.80, L = (t) => t - t0;
    const box = (yy, at, checkAt) => {
      const d = drawX(40, 34, checkAt, 0.3);
      return [rect({ x: 170, y: y(yy), width: 76, height: 76, radius: 20, fill: C.accSoft, strokeColor: C.acc, strokeWidth: 3, at, animate: [fadeIn(0, 0.12)] }),
        rect({ x: 170, y: y(yy), width: 76, height: 76, radius: 20, fill: C.acc, at: checkAt, animate: [fadeIn(0, 0.1), { property: "scale", keyframes: K([0, 0.7, EASE], [0.2, 1]) }] }),
        path({ x: 188, y: y(yy + 20), width: 40, height: 34, d: "M 3 18 L 14 30 L 37 4", stroke: { width: 7, color: "#FFFFFF", cap: "round" }, mask: d.mask, animate: [d.anim] })];
    };
    const r2 = L(20.61 - A), ck2 = L(21.29 - A);
    scene("7 checklist", t0, t1, [
      label("LES 2 CONDITIONS", { size: 34, x: 170, y: y(990), color: C.grey, animate: [fadeIn(0, 0.2)] }),
      frame({ x: 0, y: 0, width: W, height: 640, layout: "none", animate: [fadeIn(0, 0.15), { property: "offsetX", keyframes: K([0, 40, EASE], [0.3, 0]) }] },
        [...box(1080, 0, 0.1), label("Détention ≥ 2 ans", { size: 48, x: 280, y: y(1090) })]),
      frame({ x: 0, y: 0, width: W, height: 640, layout: "none", at: r2, animate: [fadeIn(0, 0.15), { property: "offsetX", keyframes: K([0, 40, EASE], [0.3, 0]) }] },
        [...box(1250, 0, ck2 - r2), label("du capital", { size: 48, x: 280 + 150, y: y(1260) })]),
      // mini counter « ≥ 5 % » inside the row, pulses on « capital »
      frame({ x: 280, y: y(1244), width: 140, height: 84, layout: "none", origin: "center", at: ck2, background: C.accSoft, radius: 20,
        motion: { timeline: { at: 0, duration: 0.6, easing: EXPO, targets: [{ target: "c5", counter: { from: 0, to: 5, prefix: "≥ ", suffix: " %" } }] } },
        animate: [fadeIn(0, 0.1), { property: "scale", keyframes: K([0, 0.7, EASE], [0.25, 1, "hold"], [L(23.13 - A) - ck2, 1, EASE], [L(23.13 - A) - ck2 + 0.15, 1.1, EASE], [L(23.13 - A) - ck2 + 0.35, 1]) }] },
        [frame({ name: "c5", x: 0, y: 12, width: 140, height: 62, layout: "none" }, [text("≥ 5 %", { x: 0, y: 0, width: 140, height: 62, align: "center", fontFamily: FONT, fontWeight: 800, fontSize: 46, color: C.acc })])]),
    ]);
    iris(23.80);
  }

  // --- 8 [23.80 → 28.20] toggle « activer » + RÉGIME MÈRE-FILLE ---
  {
    const t0 = 23.80, t1 = 28.20, L = (t) => t - t0, on = L(25.03 - A), kin = L(26.85 - A);
    const w1 = tw("RÉGIME", 104), w2 = tw("MÈRE-FILLE", 104);
    const BUMP = { property: "scale", keyframes: K([0, 1, "hold"], [on - 0.1 - 0.05, 1, EASE], [on + 0.05 - 0.05, 1.18, EASE], [on + 0.3 - 0.05, 1]) };
    scene("8 régime mère-fille", t0, t1, [
      frame({ x: (W - 150) / 2, y: y(975), width: 150, height: 150, layout: "none", origin: "center", at: 0.05,
        motion: { enter: { from: { scale: 0.6 }, duration: 0.5, easing: SPRING } }, animate: [fadeIn(0, 0.12)] },
        [icon("toggle-left", { x: 5, y: 5, size: 140, color: "#B9C0BC", strokeWidth: 2, animate: [BUMP, { property: "opacity", keyframes: K([0, 1, "hold"], [on - 0.05, 1, "linear"], [on + 0.05, 0]) }] }),
          icon("toggle-right", { x: 5, y: 5, size: 140, color: C.acc, strokeWidth: 2, animate: [BUMP, { property: "opacity", keyframes: K([0, 0, "hold"], [on - 0.05, 0, "linear"], [on + 0.05, 1]) }] })]),
      ...impact(540, y(1050), on, C.acc, 110),
      label("activé", { size: 36, x: 540 - tw("activé", 36) / 2, width: tw("activé", 36), align: "center", y: y(1122), color: C.acc, at: on + 0.3, animate: [fadeIn(0, 0.15), { property: "offsetX", keyframes: K([0, -14, EASE], [0.3, 0]) }] }),
      frame({ x: 0, y: y(1170), width: W, height: 290, layout: "none", origin: "center", at: kin,
        motion: { enter: { from: { scale: 1.35 }, duration: 0.3, easing: EASE } },
        animate: [fadeIn(0, 0.1), { property: "blur", keyframes: K([0, 10, EASE], [0.25, 0]) }] },
        [label("RÉGIME", { size: 104, x: (W - w1) / 2, y: 0, width: w1, align: "center" }),
          label("MÈRE-FILLE", { size: 104, x: (W - w2) / 2, y: 128, width: w2, align: "center", color: C.acc })]),
      (() => { const d = drawX(w2 * 0.8, 20, kin + 0.35, 0.55); return path({ x: (W - w2 * 0.8) / 2, y: y(1438), width: w2 * 0.8, height: 20, d: `M 2 12 Q ${w2 * 0.4} 2 ${w2 * 0.8 - 2} 10`, stroke: { width: 9, color: C.acc, cap: "round" }, mask: d.mask, animate: [d.anim] }); })(),
    ], { exit: SWIPE_OUT, blur: true });
  }

  // --- 9 [28.20 → 35.60] 1 règle simple ; Filiale → € → Société mère ---
  const MERE = { x: (W - 470) / 2, y: 1000, w: 470, h: 116 };
  {
    const t0 = 28.20, t1 = 35.60, L = (t) => t - t0;
    const fil = L(32.49 - A), verse = L(33.03 - A), mere = L(34.71 - A), hdrOut = fil - 0.1;
    scene("9 flux filiale", t0, t1, [
      // header: badge « 1 » + subtitle + « règle simple » — collapses before the flow needs the space
      frame({ x: 0, y: 0, width: W, height: 640, layout: "none", duration: hdrOut + 0.25,
        animate: [{ property: "offsetY", keyframes: K([0, 0, "hold"], [hdrOut, 0, EASE], [hdrOut + 0.25, -40]) },
          { property: "opacity", keyframes: K([0, 1, "hold"], [hdrOut, 1, EASE], [hdrOut + 0.24, 0]) }] }, [
        frame({ x: 210, y: y(1100), width: 150, height: 150, layout: "none", origin: "center", background: C.acc, radius: 75, at: 0.1,
          animate: [fadeIn(0, 0.12), { property: "scale", keyframes: K([0, 0.5, EASE], [0.3, 1.08, EASE], [0.45, 1, "hold"], [fil - 0.2 - 0.1, 1, EASE], [fil + 0.15 - 0.1, 0.6]) }] },
          [label("1", { size: 100, x: 0, y: 10, width: 150, align: "center", color: "#FFFFFF" })]),
        label("règle", { size: 84, x: 400, y: y(1090), at: L(31.25 - A), animate: [fadeIn(0, 0.12), { property: "offsetY", keyframes: K([0, 20, EASE], [0.3, 0]) }] }),
        label("simple", { size: 84, x: 400, y: y(1180), color: C.acc, at: L(31.53 - A), animate: [fadeIn(0, 0.12), { property: "offsetY", keyframes: K([0, 20, EASE], [0.3, 0]) }] }),
        label("Régime mère-fille", { size: 38, weight: 600, x: 400, y: y(1044), color: C.grey, at: L(29.43 - A), animate: [fadeIn(0, 0.2), { property: "offsetX", keyframes: K([0, -20, EASE], [0.3, 0]) }] }),
      ]),
      card("Filiale", { x: (W - 340) / 2, y: y(1400), w: 340, h: 112, icon: "briefcase", size: 46, at: fil }),
      (() => { const d = drawY(20, 250, verse, 0.6, true); return path({ x: 530, y: y(1140), width: 20, height: 250, d: "M 10 248 L 10 2", stroke: { width: 6, color: C.acc, cap: "round" }, dash: [16, 14], mask: d.mask, animate: [d.anim] }); })(),
      ...flow(540, y(1380), 540, y(1150), verse + 0.3, t1 - t0 - verse - 0.6, C.acc, "€"),
      label("dividendes", { size: 38, weight: 600, x: 580, y: y(1250), color: C.acc, at: L(33.59 - A), animate: [fadeIn(0, 0.2), { property: "offsetX", keyframes: K([0, -16, EASE], [0.3, 0]) }] }),
      frame({ x: MERE.x, y: y(MERE.y), width: MERE.w, height: MERE.h, layout: "none", origin: "center", at: mere,
        animate: [fadeIn(0, 0.12), { property: "scale", keyframes: K([0, 0.6, EASE], [0.3, 1.06, EASE], [0.45, 1, "hold"], [t1 - t0 - mere - 0.3, 1, EASE], [t1 - t0 - mere - 0.001, 1.12]) }] },
        [card("Société mère", { x: 0, y: 0, w: MERE.w, h: MERE.h, icon: "building-2", iconColor: C.acc, size: 46, still: true })]),
    ]);
  }

  // --- 10 [35.60 → 41.00] celle du dessus ; exonérés à 95 % (counter + gauge) ---
  {
    const t0 = 35.60, t1 = 41.00, L = (t) => t - t0;
    const upAt = L(36.15 - A), gAt = L(37.94 - A), cAt = L(39.36 - A), GX = 150, GW = 780, cw = tw("95 %", 150);
    scene("10 exonérés 95 %", t0, t1, [
      frame({ x: MERE.x, y: y(MERE.y), width: MERE.w, height: MERE.h, layout: "none", origin: "center", animate: [{ property: "scale", keyframes: K([0, 1.12, "hold"], [0.4, 1.12, EASE], [0.8, 1]) }] },
        [card("Société mère", { x: 0, y: 0, w: MERE.w, h: MERE.h, icon: "building-2", iconColor: C.acc, size: 46, still: true })]),
      pop({ x: MERE.x + MERE.w + 18, y: y(MERE.y + 18), width: 80, height: 80, background: C.accSoft, radius: 40, at: upAt,
        animate: [{ property: "offsetY", keyframes: K([0, 0, "hold"], [0.5, 0, EASE], [0.8, -8, EASE], [1.1, 0]) }] },
        [icon("arrow-up", { x: 12, y: 12, size: 56, color: C.acc, strokeWidth: 2.5 })]),
      label("celle du dessus", { size: 34, weight: 600, x: MERE.x + 20, y: y(MERE.y - 44 + 170), color: C.grey, at: upAt + 0.1, animate: [fadeIn(0, 0.2)] }),
      // gauge + « exonérés »
      frame({ x: 0, y: 0, width: W, height: 640, layout: "none", at: gAt, animate: [fadeIn(0, 0.15), { property: "offsetY", keyframes: K([0, 20, EASE], [0.3, 0]) }] }, [
        label("exonérés", { size: 44, x: GX, y: y(1250), color: C.acc }),
        rect({ x: GX, y: y(1420), width: GW, height: 48, radius: 24, fill: C.soft, strokeColor: C.line, strokeWidth: 2 }),
        rect({ x: GX, y: y(1420), width: GW, height: 48, radius: 24, fill: C.acc, mask: { shape: "rectangle", x: -1, y: -2, width: 2, height: 52 },
          animate: [{ property: "maskWidth", keyframes: K([0, 2, "hold"], [cAt - gAt, 2, EXPO], [cAt - gAt + 1.2, 2 * GW * 0.95]) }] }),
      ]),
      frame({ x: GX + GW - cw, y: y(1236), width: cw, height: 196, layout: "none", origin: "center", at: cAt,
        motion: { timeline: { at: 0, duration: 1.2, easing: EXPO, targets: [{ target: "c95", counter: { from: 0, to: 95, suffix: " %" } }] } },
        animate: [fadeIn(0, 0.08), { property: "scale", keyframes: K([0, 0.8, EASE], [0.25, 1, "hold"], [1.2, 1, EASE], [1.35, 1.08, EASE], [1.55, 1]) }] },
        [frame({ name: "c95", x: 0, y: 0, width: cw, height: 196, layout: "none" }, [text("95 %", { x: 0, y: 0, width: cw, height: 196, align: "right", fontFamily: FONT, fontWeight: 800, fontSize: 150, color: C.acc })])]),
      ...impact(GX + GW - cw / 2, y(1334), cAt, C.acc, 130),
    ]);
    wipe(41.00);
  }

  // --- 11 [41.00 → 46.40] bar 100 000 € → only the 5 000 € slice stays « réintégrés » ---
  {
    const t0 = 41.00, t1 = 46.40, L = (t) => t - t0;
    const barAt = L(42.42 - A), slice = L(43.99 - A), reint = L(45.55 - A), BX = 110, BW = 860, SW = 150, BY = 1200;
    scene("11 barres", t0, t1, [
      label("CONCRÈTEMENT", { size: 40, x: BX, y: y(990), color: C.grey, at: L(41.22 - A), motion: { by: "character", from: { opacity: 0, y: 12 }, at: 0, duration: 0.35, overlap: 0.6, easing: "ease-out" } }),
      label("100 000 €", { size: 56, x: BX, y: y(1100), at: barAt, animate: [fadeIn(0, 0.12), { property: "offsetY", keyframes: K([0, 16, EASE], [0.3, 0]) }] }),
      // full bar: elastic growth from the left, then turns light grey except the last slice
      rect({ x: BX, y: y(BY), width: BW, height: 110, radius: 22, fill: C.acc, at: barAt, mask: { shape: "rectangle", x: -1, y: -4, width: 2, height: 118 },
        animate: [{ property: "maskWidth", keyframes: K([0, 2, EASE], [0.5, 2 * BW + 4]) },
          { property: "scaleY", keyframes: K([0, 1, "hold"], [0.45, 1, EASE], [0.55, 1.12, EASE], [0.75, 1]) },
          { property: "color", keyframes: K([0, C.acc, "hold"], [slice - barAt, C.acc, "linear"], [slice - barAt + 0.25, "#DDE2DF"]) }] }),
      label("exonéré", { size: 40, weight: 600, x: BX + 36, y: y(BY + 30), color: C.grey, at: slice + 0.2, animate: [fadeIn(0, 0.2)] }),
      frame({ x: BX + BW - SW, y: y(BY), width: SW, height: 110, layout: "none", origin: "center", at: slice,
        motion: { enter: { from: { scaleY: 1.3, scaleX: 1.1 }, duration: 0.5, easing: SPRING } }, animate: [fadeIn(0, 0.06)] },
        [rect({ x: 0, y: 0, width: SW, height: 110, radius: 22, fill: C.acc2 })]),
      label("5 000 €", { size: 56, x: BX + BW - tw("5 000 €", 56), y: y(1100), width: tw("5 000 €", 56), align: "right", color: C.acc2, at: slice, animate: [fadeIn(0, 0.12), { property: "offsetY", keyframes: K([0, 16, EASE], [0.3, 0]) }] }),
      frame({ x: BX + BW - 330, y: y(BY + 140), width: 330, height: 80, layout: "row", justify: "end", align: "center", gap: 10, at: reint, animate: [fadeIn(0, 0.15), { property: "offsetY", keyframes: K([0, 16, EASE], [0.3, 0]) }] },
        [icon("corner-left-up", { size: 52, color: C.acc2, strokeWidth: 2.5 }), label("réintégrés", { size: 44, color: C.acc2 })]),
    ], { exit: SWIPE_OUT, blur: true });
  }

  let CONFETTI = null;
  // --- 12 [46.40 → 49.87] final receipt: Résultat imposable de la holding : + 5 000 € ; confetti ---
  {
    const t0 = 46.40, t1 = D.DUR, L = (t) => t - t0;
    const l1 = L(46.93 - A), l2 = L(47.81 - A), amt = L(48.10), hold = L(49.37 - A), conf = L(49.2), RX2 = 150, RW2 = 780;
    const confetti = [];
    const COLS = [C.acc, "#5FB38F", "#A8D5BF", C.acc];
    for (let i = 0; i < 26; i++) {
      const a = -Math.PI / 2 + ((i / 25) - 0.5) * 3.0, sp = 300 + (i * 37) % 180, dx = Math.cos(a) * sp, dy = Math.sin(a) * sp;
      confetti.push(rect({ x: 540 - 6, y: 1500, width: 12, height: 20, radius: 3, fill: COLS[i % 4],
        animate: [{ property: "offsetX", keyframes: K([0, 0, EASE], [0.8, dx * 1.3]) },
          { property: "offsetY", keyframes: K([0, 0, EASE], [0.35, dy, "ease-in"], [0.8, dy + 260]) },
          { property: "rotation", keyframes: K([0, 0, "linear"], [0.8, (i % 2 ? 1 : -1) * (240 + i * 20)]) },
          { property: "opacity", keyframes: K([0, 1, "hold"], [0.55, 1, EASE], [0.8, 0]) }] }));
    }
    scene("12 reçu final", t0, t1, [
      rect({ x: RX2, y: y(990), width: RW2, height: 500, radius: 30, fill: "#FFFFFF", strokeColor: C.acc, strokeWidth: 4, shadow: { x: 0, y: 14, blur: 40, color: "#0000001C" } }),
      rect({ x: RX2, y: y(990), width: RW2, height: 20, radius: 10, fill: C.acc }),
      label("Résultat imposable", { size: 54, x: RX2 + 50, y: y(1060), at: l1, animate: [fadeIn(0, 0.12), { property: "offsetY", keyframes: K([0, 18, EASE], [0.3, 0]) }] }),
      label("de la holding", { size: 54, weight: 600, x: RX2 + 50, y: y(1136), color: C.grey, at: l2, animate: [fadeIn(0, 0.12), { property: "offsetY", keyframes: K([0, 18, EASE], [0.3, 0]) }] }),
      (() => { const d = drawX(RW2 - 100, 8, amt - 0.3, 0.4); return path({ x: RX2 + 50, y: y(1236), width: RW2 - 100, height: 8, d: `M 2 4 L ${RW2 - 102} 4`, stroke: { width: 3, color: C.fg, cap: "round" }, dash: [10, 10], mask: d.mask, animate: [d.anim] }); })(),
      frame({ x: (W - tw("+ 5 000 €", 120)) / 2, y: y(1280), width: tw("+ 5 000 €", 120), height: 160, layout: "none", origin: "center", at: amt,
        motion: { enter: { from: { scale: 1.7 }, duration: 0.5, easing: SPRING } }, animate: [fadeIn(0, 0.08)] },
        [label("+ 5 000 €", { size: 120, x: 0, y: 0, color: C.acc })]),
      pop({ x: RX2 + RW2 - 140, y: y(1070), width: 100, height: 100, background: C.accSoft, radius: 50, at: hold },
        [icon("building-2", { x: 20, y: 20, size: 60, color: C.acc, strokeWidth: 2 })]),
    ], { enter: SWIPE_IN, blur: true });
    CONFETTI = { nodes: confetti, at: 49.2 };
  }

  // ================= end card 2 s (no handle: none provided) + fade to white =================
  {
    const t1 = "Abonne-toi", t2 = "Régime mère-fille : 95 % exonérés";
    p.compose([
      rect({ x: 0, y: 0, width: W, height: H, fill: C.bg, effects: [grain(0.028)], animate: [{ property: "opacity", from: 0, to: 1, duration: 0.25 }] }),
      pop({ x: (W - 150) / 2, y: 690, width: 150, height: 150, background: C.accSoft, radius: 75, at: D.DUR + 0.1, duration: D.END - 0.1 },
        [icon("bell", { x: 35, y: 35, size: 80, color: C.acc, strokeWidth: 2 })]),
      text(t1, { x: (W - tw(t1, 88)) / 2, y: 880, width: tw(t1, 88), height: 116, fontFamily: FONT, fontWeight: 800, fontSize: 88, color: C.fg,
        motion: { by: "word", from: { opacity: 0, y: 18 }, at: 0.2, duration: 0.4, overlap: 0.5, easing: "ease-out" } }),
      text(t2, { x: (W - tw(t2, 42, 600)) / 2, y: 1010, width: tw(t2, 42, 600), height: 56, fontFamily: FONT, fontWeight: 600, fontSize: 42, color: C.acc,
        animate: [{ property: "opacity", keyframes: K([0, 0, "hold"], [0.45, 0, EASE], [0.75, 1]) }] }),
      rect({ x: 0, y: 0, width: W, height: H, fill: "#FFFFFF", animate: [{ property: "opacity", keyframes: K([0, 0, "hold"], [D.END - 0.4, 0, EASE], [D.END - 0.001, 1]) }] }),
    ], { at: D.DUR, dur: D.END, name: "end card" });
  }

  // confetti (0.8 s, final positive resolution) rides over the scene-12 -> end-card cut
  p.compose(CONFETTI.nodes, { at: CONFETTI.at, dur: 0.8, name: "confetti" });

  const mode = process.env.REEL_MODE || "frames";
  if (mode === "frames") {
    const only = process.env.REEL_TIMES ? process.env.REEL_TIMES.split(",").map(Number) : D.sheet;
    for (const t of only) await p.frame(t, `renders/f_${t.toFixed(2)}.png`);
  } else if (mode === "draft") {
    await p.render("renders/draft.mp4", { draft: true, concurrency: 3 });
  } else if (mode === "master") {
    await p.render("renders/master.mp4", { depth: 8, bitrate: 10_000_000, concurrency: 3 });
  }
};
