// Reel 4 « Les 5 meilleurs pays pour créer ta société en 2026 » (n°1 Hong Kong) — 100 % B-roll, kinetic text, VFX layer.
// Higgsedit v0.14, 1080x1920 @ 60 fps. Generated by gen_edit.py (screens, shots, scores, HK outline). Audio (audio/music.py) is muxed after render.
// Safe zones: nothing important in the top 250 px or the bottom 350 px (y 250–1570).
import { createRequire } from "node:module";

const D = /*__DATA__*/null;
const W = 1080, H = 1920, FONT = "Montserrat";
const C = { fg: "#FFFFFF", bk: "#0A0A0A", acc: D.ACC, acc2: D.ACC2, ok: D.OK, dim: "#FFFFFFB8" };
const EASE = [0.2, 0.8, 0.2, 1], EXPO = [0.16, 1, 0.3, 1];
const SPRING = { kind: "spring", stiffness: 300, damping: 22 };
const SHADOW = { x: 0, y: 8, blur: 32, color: "#00000073" };          // 0/8/32 at 45 %
const MEDIA = "/home/user/w4";
const DROP = D.DROP, FR = 1 / 60;

const require = createRequire("/opt/fable/package.json");
const { GlobalFonts, createCanvas } = require("@napi-rs/canvas");
for (const w of [600, 800, 900]) GlobalFonts.registerFromPath(`${MEDIA}/reel/fonts/montserrat-${w}.woff2`, `M${w}`);
const ctx = createCanvas(4, 4).getContext("2d");
const mw = (s, size, wt = 800) => { ctx.font = `${size}px M${wt}`; return ctx.measureText(s).width; };
const tw = (s, size, wt = 800) => Math.ceil(mw(s, size, wt) * 1.04) + 8;

// ---------------- grade: exposure, saturation, contrast, tint, highlight tint, vignette (20 %), grain (<= 0.04), chromatic aberration (px)
const GRADE = `vec4 pixel(vec2 uv){
  vec2 px = vec2(u_ca, 0.0) / u_resolution;
  vec4 c = texture(u_src, uv);
  vec3 s = vec3(texture(u_src, uv + px).r, c.g, texture(u_src, uv - px).b);
  vec3 g = s * u_exp;
  float l = dot(g, vec3(0.2126, 0.7152, 0.0722));
  g = mix(vec3(l), g, u_sat);
  g = (g - 0.5) * u_con + 0.5 + u_lift;
  g *= vec3(u_r, u_g, u_b);
  float hl = smoothstep(0.55, 1.0, l);
  g = mix(g, g * vec3(u_hr, u_hg, u_hb), hl);
  float d = distance(uv, vec2(0.5));
  g *= 1.0 - u_vig * smoothstep(0.3, 0.9, d);
  float n = fract(sin(dot(floor(uv * u_resolution / 2.0) + floor(u_time * 24.0) * 17.0, vec2(12.9898, 78.233))) * 43758.5453) - 0.5;
  g += n * u_grain;
  return vec4(clamp(g, 0.0, 1.0) * c.a, c.a);
}`;
const LOOK = {   // brief: countdown cold/contrasted/slightly desaturated · HK warm neon night, deep blacks, accent in highlights · CTA clean & warm
  cold: { exp: 0.96, sat: 0.78, con: 1.16, lift: -0.02, r: 0.94, g: 1.0, b: 1.08, hr: 0.98, hg: 1.0, hb: 1.04, vig: 0.2, grain: 0.035, ca: 0 },
  neon: { exp: 1.0, sat: 1.18, con: 1.18, lift: -0.035, r: 1.06, g: 0.98, b: 0.94, hr: 1.10, hg: 0.97, hb: 0.80, vig: 0.2, grain: 0.035, ca: 0 },
  trap: { exp: 0.88, sat: 0.6, con: 1.14, lift: -0.03, r: 0.9, g: 0.98, b: 1.12, hr: 0.95, hg: 1.0, hb: 1.08, vig: 0.28, grain: 0.04, ca: 0 },
  warm: { exp: 1.03, sat: 1.08, con: 1.06, lift: -0.01, r: 1.06, g: 1.0, b: 0.92, hr: 1.05, hg: 1.0, hb: 0.92, vig: 0.2, grain: 0.03, ca: 0 },
};
const lookAt = (t) => t < DROP ? "cold" : t < 48.5 ? "neon" : t < 51 ? "trap" : "warm";
const grade = (t, extra = {}) => ({ kind: "shader", params: { glsl: GRADE, ...LOOK[lookAt(t)], ...extra } });
// luma wipe: the incoming shot appears through its own luminance (dark first), u_prog 0 -> 1
const LUMA = `vec4 pixel(vec2 uv){
  vec4 c = texture(u_src, uv);
  float l = dot(c.rgb, vec3(0.299, 0.587, 0.114));
  float a = smoothstep(l - 0.12, l + 0.12, u_prog * 1.3 - 0.15);
  return vec4(c.rgb * c.a * a, c.a * a);
}`;
// luma key for remove_background output (subject on black): alpha from brightness, so the cut-out can sit above "text behind object"
const KEY = `vec4 pixel(vec2 uv){
  vec4 c = texture(u_src, uv);
  float a = smoothstep(0.04, 0.12, max(c.r, max(c.g, c.b)));
  return vec4(c.rgb * a, a);
}`;
// light leak (GLSL, used once on the reveal): warm moving blobs, screen-blended
const LEAK = `vec4 pixel(vec2 uv){
  float t = u_time * 0.6;
  vec2 p1 = vec2(0.15 + 0.25 * sin(t), 0.25 + 0.1 * cos(t * 1.3));
  vec2 p2 = vec2(0.85 - 0.2 * cos(t * 0.8), 0.7 + 0.12 * sin(t));
  float a = exp(-8.0 * distance(uv, p1)) + 0.8 * exp(-7.0 * distance(uv, p2));
  vec3 col = mix(vec3(1.0, 0.55, 0.2), vec3(1.0, 0.82, 0.45), uv.y);
  float o = clamp(a, 0.0, 1.0) * u_amt;
  return vec4(col * o, o);
}`;

const K = (...pairs) => pairs.map(([at, value, easing]) => ({ at, value, ...(easing ? { easing } : {}) }));
// left-to-right reveal of a box `w` wide (the node mask grows from its centre, hence 2w)
const drawX = (w, h, at, dur, ease = EASE) => ({ mask: { shape: "rectangle", x: -8, y: -6, width: 2, height: h + 12 },
  anim: { property: "maskWidth", keyframes: K([0, 2, "hold"], [Math.max(at, 0.001), 2, ease], [at + dur, 2 * w + 24]) } });
let seed = 7; const rnd = () => (seed = (seed * 16807) % 2147483647) / 2147483647;

export default async ({ project, text, rect, media, path, frame, icon }) => {
  const p = await project({ dir: "reel", size: `${W}x${H}`, fps: 60, background: C.bk });
  const files = {};
  for (const s of Object.values(D.shots)) if (!files[s.file]) files[s.file] = await p.add(`${MEDIA}/${s.file}`);
  const flags = {};
  for (const c of ["ee", "ae", "us", "sg", "hk"]) flags[c] = await p.add(`${MEDIA}/flags/${c}.png`);
  const mattes = {};
  for (const [k, f] of Object.entries(D.mattes || {})) mattes[k] = await p.add(`${MEDIA}/${f}`);
  const book = D.book ? await p.add(`${MEDIA}/${D.book}`) : null;

  // One full-length compose per layer (the script lane allocator mis-maps composes that share a start time);
  // children carry absolute at/duration inside a [0, DUR] parent.
  const LAYERS = {};
  const ORDER = ["shots", "behind", "fg", "legibility", "hud", "cards", "text", "fx"];
  const put = (layer, node, at, dur) => (LAYERS[layer] ||= []).push(
    frame({ x: 0, y: 0, width: W, height: H, layout: "none", at, duration: dur }, Array.isArray(node) ? node : [node]));
  const T = (s, o) => text(s, { fontFamily: FONT, fontWeight: 800, color: C.fg, shadow: SHADOW, ...o });

  // ============================ picture ============================
  // segments: one per screen (screen 2 splits Dubaï -> New York); screens 21–23 share s21 (slowed 0.5x before import)
  const segs = [];
  for (const s of D.screens) {
    const last = segs[segs.length - 1];
    if (s.tr === "none" && last) { last.t1 = s.t1; continue; }
    if (s.c.split) {
      segs.push({ shot: s.shot, t0: s.t0, t1: s.t0 + s.c.split.at, tr: s.tr, n: s.n });
      segs.push({ shot: s.c.split.shot, t0: s.t0 + s.c.split.at, t1: s.t1, tr: s.c.split.tr, n: s.n });
    } else segs.push({ shot: s.shot, t0: s.t0, t1: s.t1, tr: s.tr, n: s.n });
  }
  const impactsAt = new Set(D.screens.filter((s) => ["cd_title", "hk", "hk3", "reveal"].includes(s.kind)).map((s) => s.t0));
  const IN = { zoom: 0.3, whip: 0.25, push: 0.3, luma: 0.35, iris: 0.35, blur: 0.3, open: 0.4, black: 0.0 };
  const OUT = { zoom: 0.15, whip: 0.15, push: 0.15 };
  const buildSeg = (g, i, fileH, pre = []) => {
    const sh = D.shots[g.shot], next = segs[i + 1];
    const tin = IN[g.tr] || 0, tout = next && OUT[next.tr] ? OUT[next.tr] : 0;
    const tail = next && ["luma", "iris", "blur"].includes(next.tr) ? IN[next.tr] : 0;   // outgoing stays underneath a reveal
    const d = g.t1 - g.t0, dd = d + tail;
    const push = (t) => 1.0 + 0.06 * Math.min(t, d) / d;                               // 100 -> 106 % push-in per shot
    // media scale is anchored top-left in Higgsedit: every scale track gets offset tracks (same keys) that keep it centred
    const centred = (anim) => anim.flatMap((t) => t.property !== "scale" ? [t] : [t,
      { property: "offsetX", keyframes: t.keyframes.map((k) => ({ ...k, value: -(k.value - 1) * W / 2 })) },
      { property: "offsetY", keyframes: t.keyframes.map((k) => ({ ...k, value: -(k.value - 1) * H / 2 })) }]);
    const node = (a, b, anim, effects, extra = {}) => media({ file: fileH, x: 0, y: 0, width: W, height: H, fit: "cover",
      trimStart: sh.from + a, muted: true, effects: [...pre, ...effects],
      animate: centred(anim).map((t) => t.property === "effectParam" ? { ...t, effectIndex: t.effectIndex + pre.length } : t), ...extra });
    const parts = [];
    // ---- in-transition node [0, tin)
    if (tin > 0) {
      const e = tin - 0.001, anim = [], fx = [grade(g.t0)];
      let extra = {};
      // whip / push travel 10 % of the frame while scaled 1.6x, so the frame edges never uncover black; motion blur sells the speed
      if (g.tr === "zoom") anim.push({ property: "scale", keyframes: K([0, 1.45, EASE], [e, push(e)]) }, { property: "blur", keyframes: K([0, 16, EASE], [e, 0]) });
      else if (g.tr === "whip" || g.tr === "push") anim.push({ property: "scale", keyframes: K([0, 1.6, EASE], [e, push(e)]) }, { property: "blur", keyframes: K([0, 10, EASE], [e, 0]) });
      else anim.push({ property: "scale", keyframes: K([0, push(0), "linear"], [e, push(e)]) });
      if (g.tr === "whip") anim.push({ property: "offsetX", keyframes: K([0, W * 0.1, EASE], [e, 0]) });
      if (g.tr === "push") anim.push({ property: "offsetY", keyframes: K([0, H * 0.1, EASE], [e, 0]) });
      if (g.tr === "blur") anim.push({ property: "opacity", keyframes: K([0, 0, EASE], [e, 1]) }, { property: "blur", keyframes: K([0, 22, EASE], [e, 0]) });
      if (g.tr === "luma") { fx.push({ kind: "shader", params: { glsl: LUMA, prog: 0 } });
        anim.push({ property: "effectParam", effectIndex: 1, effectParam: "prog", keyframes: K([0, 0, EASE], [e, 1]) }); }

      if (["whip", "zoom"].includes(g.tr) || impactsAt.has(g.t0))
        anim.push({ property: "effectParam", effectIndex: 0, effectParam: "ca", keyframes: K([0, 1.5, EASE], [e, 0]) });
      // iris / shape match: the incoming shot is revealed from the centre (frame reveal), an accent frame rides the edge (fx layer)
      parts.push(frame({ x: 0, y: 0, width: W, height: H, layout: "none", clip: true, at: 0, duration: tin, motionBlur: { samples: 6, shutter: 0.5 },
        ...(g.tr === "iris" ? { reveal: { from: "center", at: 0, duration: e, easing: EASE } } : {}) }, [node(0, tin, anim, fx, extra)]));
    }
    // ---- body [tin, d - tout) (+ tail under the next reveal): slow push-in, no motion blur needed (< 250 px/s)
    const b0 = tin, b1 = dd - tout;
    parts.push(frame({ x: 0, y: 0, width: W, height: H, layout: "none", clip: true, at: b0, duration: b1 - b0 },
      [node(b0, b1, [{ property: "scale", keyframes: K([0, push(b0), "linear"], [b1 - b0 - 0.001, push(b1)]) }], [grade(g.t0 + b0)])]));
    // ---- out-transition node [d - tout, d)
    if (tout > 0) {
      const e = tout - 0.001, a0 = d - tout, anim = [];
      if (next.tr === "zoom") anim.push({ property: "scale", keyframes: K([0, push(a0), "ease-in"], [e, push(d) * 1.5]) }, { property: "blur", keyframes: K([0, 0, "ease-in"], [e, 16]) });
      else if (next.tr === "whip" || next.tr === "push") anim.push({ property: "scale", keyframes: K([0, push(a0), "ease-in"], [e, 1.6]) }, { property: "blur", keyframes: K([0, 0, "ease-in"], [e, 10]) });
      else anim.push({ property: "scale", keyframes: K([0, push(a0), "linear"], [e, push(d)]) });
      if (next.tr === "whip") anim.push({ property: "offsetX", keyframes: K([0, 0, "ease-in"], [e, -W * 0.1]) });
      if (next.tr === "push") anim.push({ property: "offsetY", keyframes: K([0, 0, "ease-in"], [e, -H * 0.1]) });
      parts.push(frame({ x: 0, y: 0, width: W, height: H, layout: "none", clip: true, at: a0, duration: tout, motionBlur: { samples: 6, shutter: 0.5 } },
        [node(a0, d, anim, [grade(g.t0 + a0)])]));
    }
    return { parts, dd };
  };
  segs.forEach((g, i) => {
    const sh = D.shots[g.shot];
    const { parts, dd } = buildSeg(g, i, files[sh.file]);
    put("shots", frame({ x: 0, y: 0, width: W, height: H, layout: "none" }, parts), g.t0, dd);
    if (mattes[g.shot]) {   // cut-out of the same frames (Higgsfield remove_background), same motion, keyed above the "behind" word
      const m = buildSeg(g, i, mattes[g.shot], [{ kind: "shader", params: { glsl: KEY } }]);
      put("fg", frame({ x: 0, y: 0, width: W, height: H, layout: "none" }, m.parts), g.t0, Math.min(m.dd, g.t1 - g.t0));
    }
  });

  // ============================ legibility ============================
  // lower third: black 0 -> 55 %; soft centre band behind the text block (max 30 %)
  put("legibility", [
    rect({ x: 0, y: 1280, width: W, height: 640, fill: { kind: "linear", angle: 180, stops: [{ offset: 0, color: "#000000", opacity: 0 }, { offset: 1, color: "#000000", opacity: 0.55 }] } }),
    rect({ x: 0, y: 420, width: W, height: 1000, fill: { kind: "linear", angle: 180, stops: [{ offset: 0, color: "#000000", opacity: 0 },
      { offset: 0.3, color: "#000000", opacity: 0.3 }, { offset: 0.7, color: "#000000", opacity: 0.3 }, { offset: 1, color: "#000000", opacity: 0 }] } }),
  ], 0, D.DUR);

  // ============================ helpers ============================
  // kinetic line: segments positioned at the measured advance of the text before them; one accent colour; word motion
  const line = (ln, size, y, { at = 0, dur, accColor = C.acc, color = C.fg, wt = 800, center = true, x = 90, words = true, glow = false } = {}) => {
    let pre = ""; const segsN = [];
    for (const g of ln) {
      const lead = g.t.match(/^ */)[0], s = g.t.slice(lead.length);
      const gx = mw(pre + lead, size, wt); pre += g.t;
      segsN.push(T(s, { x: Math.round(gx), y: 0, width: tw(s, size, wt) + 20, height: Math.round(size * 1.25), fontSize: size, fontWeight: wt,
        color: g.acc ? accColor : color, ...(g.acc && glow ? { shadow: { x: 0, y: 0, blur: 36, color: accColor + "AA" } } : {}),
        ...(words ? { motion: { by: "word", from: { opacity: 0, y: 28 }, at: 0, duration: 0.3, overlap: 0.5, easing: "ease-out" } } : {}) }));
    }
    const w = Math.ceil(mw(pre, size, wt));
    return frame({ x: center ? Math.round((W - w) / 2) : x, y, width: w + 40, height: Math.round(size * 1.25), layout: "none", at, ...(dur ? { duration: dur } : {}) }, segsN);
  };
  const exitFade = (d, lead = 0.12) => ({ property: "opacity", keyframes: K([0, 1, "hold"], [d - lead, 1, EASE], [d - 0.001, 0]) });
  // glass card: blurred copy of the shot under the card (backdrop blur 24), white 8 %, 20 % white border, dark tint for legibility
  const shotAt = (t) => segs.find((g) => t >= g.t0 && t < g.t1) || segs[segs.length - 1];
  const glass = (t, x, y, w, h, { radius = 28, border = "#FFFFFF33", tint = "#00000059", fill = "#FFFFFF14" } = {}) => {
    const g = shotAt(t), sh = D.shots[g.shot];
    return [
      frame({ x: 0, y: 0, width: w, height: h, layout: "none", clip: true, radius }, [
        media({ file: files[sh.file], x: -x, y: -y, width: W, height: H, fit: "cover", trimStart: sh.from + (t - g.t0), muted: true,
          effects: [grade(t), { kind: "blur", params: { radius: 24 } }] }),
        rect({ x: 0, y: 0, width: w, height: h, fill: tint }), rect({ x: 0, y: 0, width: w, height: h, fill })]),
      rect({ x: 0, y: 0, width: w, height: h, radius, fill: "#00000000", strokeColor: border, strokeWidth: 2 }),
    ];
  };
  const rise = (at, from = 70) => ({ enter: { from: { y: from }, duration: 0.6, easing: SPRING } });   // springs overshoot: opacity stays on raw tracks
  const fadeIO = (d, fin = 0.15, fout = 0.12) => ({ property: "opacity", keyframes: K([0, 0, EASE], [fin, 1, "hold"], [d - fout, 1, EASE], [d - 0.001, 0]) });
  const fadeIn = (fin = 0.15) => ({ property: "opacity", keyframes: K([0, 0, EASE], [fin, 1]) });
  const ic = (name, size, color, sw = 2) => icon(name, { size, color, strokeWidth: sw });
  const counterFrame = (name, w, h, size, color, cfg, wt = 900, glow = false) => frame({ x: 0, y: 0, width: w, height: h, layout: "none",
    motion: { timeline: { at: cfg.at || 0, duration: cfg.dur || 0.6, easing: EXPO, targets: [{ target: name, counter: cfg.counter }] } } }, [
    frame({ name, x: 0, y: 0, width: w, height: h, layout: "none" }, [
      text(cfg.counter.prefix ? `${cfg.counter.prefix}${cfg.counter.to}${cfg.counter.suffix || ""}` : `${cfg.counter.to}${cfg.counter.suffix || ""}`,
        { x: 0, y: 0, width: w, height: h, fontFamily: FONT, fontWeight: wt, fontSize: size, color, align: "right",
          shadow: glow ? { x: 0, y: 0, blur: 30, color: color + "AA" } : SHADOW })])]);

  // scoreboard: 4 bars 440x14, expo-out 0.6 s staggered 80 ms, rolling score /10 ("NOTRE NOTE")
  const LABELS = ["IMPÔTS", "RAPIDITÉ", "BANQUE", "CRÉDIBILITÉ"];
  const scoreboard = (code, y, at, hk = false) => {
    const v = D.scores[code], avg = v.reduce((a, b) => a + b, 0) / 4, ip = Math.floor(avg + 1e-9), dec = Math.round((avg - ip) * 10);
    const kids = [];
    v.forEach((s, i) => {
      const yy = i * 62, t0 = at + i * 0.08, fw = 440 * s / 10, dx = drawX(fw, 14, t0, 0.6, EXPO);
      kids.push(text(LABELS[i], { x: 0, y: yy - 6, width: 300, height: 44, fontFamily: FONT, fontWeight: 600, fontSize: 32, color: C.dim, letterSpacing: 2, shadow: SHADOW }));
      kids.push(rect({ x: 330, y: yy + 8, width: 440, height: 14, radius: 7, fill: "#FFFFFF40" }));
      kids.push(rect({ x: 330, y: yy + 8, width: fw, height: 14, radius: 7, fill: hk ? C.acc : C.fg, mask: dx.mask, animate: [dx.anim],
        ...(hk ? { shadow: { x: 0, y: 0, blur: 22, color: C.acc + "CC" } } : {}) }));
    });
    kids.push(text("NOTRE NOTE", { x: 0, y: 4 * 62 + 22, width: 320, height: 44, fontFamily: FONT, fontWeight: 600, fontSize: 30, color: C.dim, letterSpacing: 3, shadow: SHADOW }));
    kids.push(frame({ x: 470, y: 4 * 62 + 2, width: 300, height: 90, layout: "none" }, [
      counterFrame(`score_${code}_${Math.round(at * 100)}`, 300, 90, 76, hk ? C.acc : C.fg,
        { at: at + 0.1, dur: 0.7, counter: { from: 0, to: ip, decimals: 0, suffix: `,${dec}/10` } }, 900, hk)]));
    return frame({ x: 155, y, width: 780, height: 4 * 62 + 110, layout: "none" }, kids);
  };
  // giant countdown number: 420 px Black, 12 px accent extrusion, scale 1.5 -> 1 with blur on entrance (+ impact), slide-up exit
  const bigNum = (s, size, y, dur, { exitUp = true } = {}) => {
    const w = tw(s, size, 900) + 24, h = Math.round(size * 1.1), x = Math.round((W - w) / 2);
    const ext = [];
    for (let i = 12; i >= 1; i--) ext.push(text(s, { x: i, y: i, width: w, height: h, fontFamily: FONT, fontWeight: 900, fontSize: size, color: C.acc, align: "center" }));
    ext.push(text(s, { x: 0, y: 0, width: w, height: h, fontFamily: FONT, fontWeight: 900, fontSize: size, color: C.fg, align: "center", shadow: SHADOW }));
    return frame({ x, y, width: w + 14, height: h + 14, layout: "none", origin: "center", motionBlur: { samples: 6, shutter: 0.5 },
      motion: { enter: { from: { scale: 1.5 }, duration: 0.6, easing: SPRING },
        ...(exitUp ? { exit: { to: { y: -320 }, duration: 0.25, anchor: "end", easing: "ease-in" } } : {}) },
      animate: [{ property: "blur", keyframes: K([0, 14, EASE], [0.3, 0]) }, exitUp ? fadeIO(dur, 0.1, 0.25) : fadeIn(0.1)], duration: dur }, ext);
  };
  const flagNode = (c, w, h) => media({ file: flags[c], x: 0, y: 0, width: w, height: h, fit: "fill", radius: 6 });
  const countryRow = (c, name, size, y, at, numTxt) => {
    const fw = Math.round(size * 0.75 * 4 / 3), fh = Math.round(size * 0.75), gap = 24;
    const nt = numTxt ? `N°${numTxt}  ` : "";
    const wName = tw(name, size), wNum = numTxt ? tw(nt, size, 900) : 0, total = fw + gap + wNum + wName;
    const x0 = Math.round((W - total) / 2);
    return frame({ x: x0, y, width: total + 20, height: Math.round(size * 1.25), layout: "none", at }, [
      frame({ x: 0, y: Math.round(size * 0.25), width: fw, height: fh, layout: "none", motion: { enter: { from: { scale: 0.4 }, duration: 0.6, easing: SPRING } }, animate: [fadeIn(0.1)], origin: "center" },
        [flagNode(c, fw, fh)]),
      ...(numTxt ? [T(nt, { x: fw + gap, y: 0, width: wNum + 10, height: Math.round(size * 1.25), fontSize: size, fontWeight: 900, color: C.acc })] : []),
      T(name, { x: fw + gap + wNum, y: 0, width: wName + 10, height: Math.round(size * 1.25), fontSize: size,
        motion: { by: "word", from: { opacity: 0, y: 30 }, at: 0.05, duration: 0.3, overlap: 0.4, easing: "ease-out" } }),
    ]);
  };
  const checkPath = (sz, col, at) => { const dx = drawX(sz, sz, at, 0.25);
    return path({ x: 0, y: 0, width: sz, height: sz, d: `M ${sz * 0.22} ${sz * 0.52} L ${sz * 0.42} ${sz * 0.72} L ${sz * 0.78} ${sz * 0.3}`,
      stroke: { color: col, width: 9, cap: "round" }, mask: dx.mask, animate: [dx.anim] }); };
  const crossPath = (sz, col, at) => { const dx = drawX(sz, sz, at, 0.25);
    return path({ x: 0, y: 0, width: sz, height: sz, d: `M ${sz * 0.28} ${sz * 0.28} L ${sz * 0.72} ${sz * 0.72} M ${sz * 0.72} ${sz * 0.28} L ${sz * 0.28} ${sz * 0.72}`,
      stroke: { color: col, width: 9, cap: "round" }, mask: dx.mask, animate: [dx.anim] }); };
  const wrap = (str, size, maxw, wt = 800) => {   // greedy word wrap on measured widths
    const out = []; let cur = "";
    for (const wd of str.split(" ")) { const tryS = cur ? cur + " " + wd : wd; if (mw(tryS, size, wt) > maxw && cur) { out.push(cur); cur = wd; } else cur = tryS; }
    if (cur) out.push(cur); return out;
  };

  // ============================ screens ============================
  for (const s of D.screens) {
    const d = s.t1 - s.t0, c = s.c, nodes = [], cards = [];
    if (s.kind === "text") {
      const sizes = c.lines.map((ln) => ln.length === 1 && ln[0].acc ? 150 : 82);
      const tot = sizes.reduce((a, z) => a + z * 1.25, 0) + 16 * (sizes.length - 1);
      let y = Math.round(900 - tot / 2);
      c.lines.forEach((ln, i) => {
        const L = line(ln, sizes[i], y, { at: 0.04 + i * 0.14, dur: d - 0.04 - i * 0.14, glow: true });
        nodes.push(L); y += Math.round(sizes[i] * 1.25) + 16;
      });
      // accent word pop: a spring scale on the accent-bearing line is carried by its word motion; add a beat-synced underline flash
    }
    if (s.kind === "criteria") {
      nodes.push(line(c.lines[0], 78, 560, { at: 0.05, dur: d - 0.05, glow: true }));
      c.items.forEach(([ico, lab], i) => {
        const cx = 90 + (i % 2) * 460, cy = 760 + Math.floor(i / 2) * 300, at = 0.5 + i * 0.5;
        cards.push(frame({ x: cx, y: cy, width: 440, height: 260, layout: "none", at, duration: d - at, motion: rise(at), animate: [fadeIn()] }, [
          ...glass(s.t0 + at, cx, cy, 440, 260),
          frame({ x: 160, y: 30, width: 120, height: 120, layout: "none" }, [ic(ico, 120, C.acc, 2)]),
          text(lab, { x: 0, y: 170, width: 440, height: 60, fontFamily: FONT, fontWeight: 600, fontSize: 44, color: C.fg, align: "center", shadow: SHADOW })]));
      });
    }
    if (s.kind === "cd_title") {
      nodes.push(bigNum(c.num, 420, 300, d));
      nodes.push(frame({ x: 0, y: 0, width: W, height: H, layout: "none", at: 0.15, duration: d - 0.15, animate: [exitFade(d - 0.15)] },
        [countryRow(c.flag, c.name, 96, 800, 0, null)]));
      cards.push(frame({ x: 0, y: 0, width: W, height: H, layout: "none", at: 0.3, duration: d - 0.3, animate: [exitFade(d - 0.3)] }, [scoreboard(c.flag, 1000, 0.05)]));
    }
    if (s.kind === "cd_pros") {
      nodes.push(frame({ x: 0, y: 0, width: W, height: H, layout: "none", animate: [exitFade(d)] }, [countryRow(c.flag, c.name, 64, 330, 0, c.num)]));
      const rows = [{ at: 0.05, col: C.ok, sym: "check", txt: c.pro, y: 760 }, { at: 1.0, col: C.acc2, sym: "cross", txt: [{ t: c.con, acc: false }], y: 1080 }];
      for (const r of rows) {
        const full = r.txt.map((g) => g.t).join(""), lines = wrap(full, 58, 650);
        const h = Math.max(200, 60 + lines.length * 72);
        const kids = [...glass(s.t0 + r.at, 90, r.y, 900, h, { border: r.col + "88" }),
          rect({ x: 0, y: 24, width: 8, height: h - 48, radius: 4, fill: r.col }),
          frame({ x: 40, y: Math.round(h / 2 - 50), width: 100, height: 100, layout: "none" }, [
            rect({ x: 0, y: 0, width: 100, height: 100, radius: 50, fill: r.col + "33", strokeColor: r.col, strokeWidth: 3 }),
            r.sym === "check" ? checkPath(100, r.col, 0.12) : crossPath(100, r.col, 0.12)])];
        let yy = Math.round(h / 2 - lines.length * 36);
        // the first line keeps the accent segment (pro: "0 %" / "Hub"), later lines are plain
        lines.forEach((ln, i) => {
          const segsL = i === 0 && r.sym === "check" ? (() => { const acc = r.txt.find((g) => g.acc); return ln.startsWith(acc.t) ? [acc, { t: ln.slice(acc.t.length), acc: false }] : [{ t: ln, acc: false }]; })()
            : [{ t: ln, acc: false }];
          kids.push(line(segsL, 58, yy, { center: false, x: 175, color: r.sym === "cross" ? C.acc2 : C.fg, glow: true }));
          yy += 72;
        });
        cards.push(frame({ x: 90, y: r.y, width: 900, height: h, layout: "none", at: r.at, duration: d - r.at, motion: rise(r.at), animate: [fadeIO(d - r.at)] }, kids));
      }
    }
    if (s.kind === "reveal") {
      // N°1 (27.067 -> 28.0), then HONG / KONG full frame + flag + full scoreboard with glow (28.0 -> 29.0)
      nodes.push(frame({ x: 0, y: 0, width: W, height: H, layout: "none", at: 0.067, duration: 0.933 }, [bigNum("N°1", 300, 640, 0.933, { exitUp: false })]));
      const hong = frame({ x: 0, y: 0, width: W, height: H, layout: "none", at: 1.0, duration: 1.0 }, [
        frame({ x: 0, y: 330, width: W, height: 640, layout: "none", origin: "center", motionBlur: { samples: 6, shutter: 0.5 },
          motion: { enter: { from: { scale: 1.25 }, duration: 0.6, easing: SPRING } }, animate: [fadeIn(0.08)] }, [
          text("HONG", { x: 0, y: 0, width: W, height: 330, fontFamily: FONT, fontWeight: 900, fontSize: 300, color: C.fg, align: "center", shadow: { x: 0, y: 0, blur: 40, color: C.acc + "99" } }),
          text("KONG", { x: 0, y: 300, width: W, height: 330, fontFamily: FONT, fontWeight: 900, fontSize: 300, color: C.fg, align: "center", shadow: { x: 0, y: 0, blur: 40, color: C.acc + "99" } })]),
        frame({ x: 492, y: 990, width: 96, height: 72, layout: "none" }, [flagNode("hk", 96, 72)]),
      ]);
      nodes.push(hong);
      cards.push(frame({ x: 0, y: 0, width: W, height: H, layout: "none", at: 1.05, duration: 0.95 }, [scoreboard("hk", 1110, 0.0, true)]));
    }
    if (s.kind === "hk" || s.kind === "trap") {
      const trap = s.kind === "trap", col = trap ? C.acc2 : C.acc;
      const parts = [];
      let y = 30;
      if (c.label) { parts.push(text(c.label, { x: 0, y, width: 900, height: 56, fontFamily: FONT, fontWeight: 600, fontSize: 44, color: C.dim, align: "center", letterSpacing: 3, shadow: SHADOW })); y += 70; }
      if (c.big) {
        const size = c.bigsize || 160, bw = 900, bh = Math.round(size * 1.15);
        const bcol = c.bigwhite ? C.fg : col;
        if (c.counter) {
          parts.push(frame({ x: 0, y, width: bw, height: bh, layout: "none" }, [counterFrame(`cnt_${s.n}`, 640, bh, size, bcol,
            { at: 0.15, dur: 0.7, counter: { from: c.counter[0], to: c.counter[1], decimals: 0, suffix: c.counter[2] } }, 900, true)]));
        } else {
          const dx = drawX(bw, bh, 0.15, 0.45);
          parts.push(frame({ x: 0, y, width: bw, height: bh, layout: "none" }, [
            text(c.big, { x: 0, y: 0, width: bw, height: bh, fontFamily: FONT, fontWeight: 900, fontSize: size, color: "#00000000", strokeColor: bcol, strokeWidth: 3, align: "center" }),
            text(c.big, { x: 0, y: 0, width: bw, height: bh, fontFamily: FONT, fontWeight: 900, fontSize: size, color: bcol, align: "center",
              shadow: { x: 0, y: 0, blur: 40, color: bcol + "99" }, mask: dx.mask, animate: [dx.anim] })]));
        }
        y += bh + 10;
      }
      c.lines.forEach((ln, i) => {
        const full = ln.map((g) => g.t).join(""), size = mw(full, 64) > 820 ? 54 : 64;
        const L = line(ln, size, y, { at: 0.35 + i * 0.25, accColor: col, glow: true });
        parts.push(L); y += Math.round(size * 1.25) + 6;
      });
      if (c.note) { parts.push(text(c.note, { x: 0, y: y + 8, width: 900, height: 52, fontFamily: FONT, fontWeight: 600, fontSize: 40, color: C.dim, align: "center", shadow: SHADOW,
        animate: [{ property: "opacity", keyframes: K([0, 0, "hold"], [0.8, 0, EASE], [1.1, 1]) }] })); y += 70; }
      const ch = y + 30, cy = trap ? 760 : 700;
      const card = frame({ x: 90, y: cy, width: 900, height: ch, layout: "none", at: 0.1, duration: d - 0.1, motion: rise(0.1),
        animate: [fadeIO(d - 0.1), ...(trap ? [{ property: "offsetX", keyframes: K([0, 0, "linear"], [0.05, 2, "linear"], [0.1, -2, "linear"], [0.15, 0]), repeat: Math.floor((d - 0.3) / 0.15) }] : [])] }, [
        ...glass(s.t0 + 0.1, 90, cy, 900, ch, trap ? { border: C.acc2 + "CC", tint: "#2A000080", fill: C.acc2 + "26" } : {}), ...parts.map((n) => n)]);
      cards.push(card);
      cards.push(frame({ x: 480, y: cy - 150, width: 120, height: 120, layout: "none", origin: "center", at: 0.05, duration: d - 0.05,
        motion: { enter: { from: { scale: 0.3 }, duration: 0.6, easing: SPRING } }, animate: [fadeIO(d - 0.05)] }, [ic(c.icon, 120, col, 2)]));
    }
    if (s.kind === "hk3") {
      c.cards.forEach(([big, lab, note], i) => {
        const at = 0.5 * i, cy = 560 + i * 280;
        const dx = drawX(330, 140, 0.1, 0.35);
        cards.push(frame({ x: 90, y: cy, width: 900, height: 240, layout: "none", at, duration: d - at, motion: rise(at), animate: [fadeIO(d - at)] }, [
          ...glass(s.t0 + at, 90, cy, 900, 240),
          text(big, { x: 40, y: 50, width: 330, height: 140, fontFamily: FONT, fontWeight: 900, fontSize: 120, color: "#00000000", strokeColor: C.acc, strokeWidth: 3 }),
          text(big, { x: 40, y: 50, width: 330, height: 140, fontFamily: FONT, fontWeight: 900, fontSize: 120, color: C.acc, shadow: { x: 0, y: 0, blur: 36, color: C.acc + "99" }, mask: dx.mask, animate: [dx.anim] }),
          text(lab, { x: 380, y: note ? 62 : 86, width: 500, height: 76, fontFamily: FONT, fontWeight: 800, fontSize: 60, color: C.fg, shadow: SHADOW }),
          ...(note ? [text(note, { x: 380, y: 140, width: 500, height: 50, fontFamily: FONT, fontWeight: 600, fontSize: 38, color: C.dim })] : [])]));
      });
    }
    if (s.kind === "cta_book" || s.kind === "cta_chips" || s.kind === "cta_end") {
      if (s.kind === "cta_book") {
        if (book) put("cards", media({ file: book, x: 90, y: 250, width: 900, height: 1100, fit: "fill" }), s.t0, D.DUR - s.t0);
        nodes.push(line(c.lines[0], 56, 1330, { at: 0.4, dur: d - 0.4, wt: 600 }));
        nodes.push(line(c.lines[1], 84, 1405, { at: 0.6, dur: d - 0.6, glow: true }));
      }
      if (s.kind === "cta_chips") {
        const rowsC = [[c.chips[0], c.chips[1]], [c.chips[2], [c.chips[3][0] + " " + c.tail, 1]]];
        rowsC.forEach((row, r) => {
          const ws = row.map(([t]) => tw(t, 44, 600) + 56), tot = ws.reduce((a, b) => a + b, 0) + 24 * (row.length - 1);
          let x = Math.round((W - tot) / 2);
          row.forEach(([t, acc], j) => {
            const at = 0.25 * (r * 2 + j), cx = x, cy = 1300 + r * 112;
            cards.push(frame({ x: cx, y: cy, width: ws[j], height: 92, layout: "none", at, duration: d - at, motion: rise(at, 40), animate: [fadeIn()] }, [
              ...glass(s.t0 + at, cx, cy, ws[j], 92, { radius: 46, border: acc ? C.acc + "CC" : "#FFFFFF40" }),
              text(t, { x: 0, y: 18, width: ws[j], height: 56, fontFamily: FONT, fontWeight: 600, fontSize: 44, color: acc ? C.acc : C.fg, align: "center" })]));
            x += ws[j] + 24;
          });
        });
      }
      if (s.kind === "cta_end") {
        const pulse = { property: "scale", keyframes: K([0, 1, "ease-in-out"], [0.25, 1.06, "ease-in-out"], [0.5, 1]), repeat: Math.floor(d / 0.5) - 1 };
        nodes.push(T("Commente", { x: 0, y: 1250, width: W, height: 110, fontSize: 88, align: "center",
          motion: { by: "word", from: { opacity: 0, y: 30 }, at: 0, duration: 0.3, easing: "ease-out" } }));
        nodes.push(frame({ x: 0, y: 1345, width: W, height: 160, layout: "none", origin: "center", animate: [pulse] }, [
          text("CODEX", { x: 0, y: 0, width: W, height: 160, fontFamily: FONT, fontWeight: 900, fontSize: 132, color: C.acc, align: "center", shadow: { x: 0, y: 0, blur: 40, color: C.acc + "AA" } })]));
        nodes.push(frame({ x: 795, y: 1385, width: 90, height: 90, layout: "none", animate: [{ property: "offsetX", keyframes: K([0, 0, "ease-in-out"], [0.25, 12, "ease-in-out"], [0.5, 0]), repeat: Math.floor(d / 0.5) - 1 }] },
          [ic("arrow-right", 90, C.acc, 3)]));
      }
    }
    if (nodes.length) put("text", frame({ x: 0, y: 0, width: W, height: H, layout: "none" }, nodes), s.t0, d);
    if (cards.length) put("cards", frame({ x: 0, y: 0, width: W, height: H, layout: "none" }, cards), s.t0, d);
  }

  // ============================ text behind object (screen 2: DUBAÏ behind the Burj Khalifa cut-out) ============================
  for (const g of segs.filter((x) => mattes[x.shot])) {
    const d = g.t1 - g.t0, word = D.mattes_word[g.shot];
    put("behind", text(word, { x: 0, y: 300, width: W, height: 280, fontFamily: FONT, fontWeight: 900, fontSize: 250, color: "#FFFFFF", align: "center", letterSpacing: 6,
      animate: [{ property: "opacity", keyframes: K([0, 0, "hold"], [0.2, 0, EASE], [0.4, 0.92, "hold"], [d - 0.2, 0.92, "ease-in"], [d - 0.001, 0]) },
        { property: "offsetY", keyframes: K([0, 40, "hold"], [0.2, 40, EASE], [0.5, 0, "linear"], [d - 0.001, -12]) }] }), g.t0, d);
  }

  // ============================ HUD (Hong Kong block 29.0 -> 48.5) ============================
  {
    const t0 = 29.0, d = 48.5 - t0, hk = D.hk;
    const grid = [];
    for (let x = -120; x <= W + 240; x += 120) grid.push(rect({ x, y: -240, width: 2, height: H + 480, fill: "#FFFFFF1F" }));
    for (let y = -240; y <= H + 240; y += 120) grid.push(rect({ x: -240, y, width: W + 480, height: 2, fill: "#FFFFFF1F" }));
    const hud = [
      frame({ x: 0, y: 0, width: W, height: H, layout: "none",
        animate: [{ property: "offsetY", keyframes: K([0, 0, "linear"], [d - 0.001, -120]) }, { property: "offsetX", keyframes: K([0, 0, "linear"], [d - 0.001, -60]) }] }, grid),
      text("22.3°N · 114.2°E", { x: 90, y: 268, width: 520, height: 48, fontFamily: FONT, fontWeight: 600, fontSize: 34, color: C.fg, letterSpacing: 2, shadow: SHADOW,
        motion: { by: "character", from: { opacity: 0 }, at: 0.1, duration: 0.05, overlap: 0, easing: "linear" } }),
    ];
    const od = drawX(hk.W, hk.H, 0.2, 0.9);
    hud.push(frame({ x: W - 90 - hk.W, y: 262, width: hk.W, height: hk.H, layout: "none" }, [
      path({ x: 0, y: 0, width: hk.W, height: hk.H, d: hk.d, stroke: { color: "#FFFFFF", width: 3, cap: "round" }, mask: od.mask, animate: [od.anim] }),
      rect({ x: hk.pin[0] - 9, y: hk.pin[1] - 9, width: 18, height: 18, radius: 9, fill: C.acc, shadow: { x: 0, y: 0, blur: 16, color: C.acc } }),
      rect({ x: hk.pin[0] - 9, y: hk.pin[1] - 9, width: 18, height: 18, radius: 9, fill: "#00000000", strokeColor: C.acc, strokeWidth: 3,
        animate: [{ property: "scale", keyframes: K([0, 1, "ease-out"], [0.95, 3.2, "hold"], [1.0, 1]), repeat: Math.floor(d) - 1 },
          { property: "opacity", keyframes: K([0, 1, "ease-out"], [0.95, 0, "hold"], [1.0, 1]), repeat: Math.floor(d) - 1 }] })]));
    // 30 dust particles (alpha 30 %), deterministic drift
    for (let i = 0; i < 30; i++) {
      const x = rnd() * W, y = 250 + rnd() * 1350, sz = 3 + rnd() * 5, vy = -(20 + rnd() * 50), vx = (rnd() - 0.5) * 30;
      hud.push(rect({ x, y, width: sz, height: sz, radius: sz / 2, fill: "#FFFFFF", opacity: 0.3,
        animate: [{ property: "offsetY", keyframes: K([0, 0, "linear"], [d - 0.001, vy * d]) }, { property: "offsetX", keyframes: K([0, 0, "linear"], [d - 0.001, vx * d]) }] }));
    }
    put("hud", frame({ x: 0, y: 0, width: W, height: H, layout: "none", animate: [{ property: "opacity", keyframes: K([0, 0, EASE], [0.3, 1, "hold"], [d - 0.3, 1, EASE], [d - 0.001, 0]) }] }, hud), t0, d);
  }

  // ============================ FX ============================
  // open: light flash from black
  put("fx", rect({ x: 0, y: 0, width: W, height: H, fill: C.bk, animate: [{ property: "opacity", keyframes: K([0, 1, EASE], [0.4, 0]) }] }), 0, 0.41);
  put("fx", rect({ x: 0, y: 0, width: W, height: H, fill: "#FFF4E0", animate: [{ property: "opacity", keyframes: K([0, 0, EASE], [0.12, 0.5, EASE], [0.4, 0]) }] }), 0, 0.41);
  // iris transitions: accent ring riding the edge of the reveal
  for (const g of segs.filter((x) => x.tr === "iris")) {
    put("fx", frame({ x: 0, y: 0, width: W, height: H, layout: "none", origin: "center", motionBlur: { samples: 6, shutter: 0.5 },
      animate: [{ property: "scale", keyframes: K([0, 0.04, EASE], [0.349, 1.04]) }, { property: "opacity", keyframes: K([0, 1, "hold"], [0.22, 1, EASE], [0.349, 0]) }] },
      [rect({ x: 0, y: 0, width: W, height: H, radius: 48, fill: "#00000000", strokeColor: C.acc, strokeWidth: 14 })]), g.t0, 0.35);
  }
  // n°1 reveal: 4 black frames, one glitch (RGB-offset bars), white flash, light leak
  put("fx", rect({ x: 0, y: 0, width: W, height: H, fill: "#000000" }), DROP, 4 * FR);
  {
    const bars = [];
    for (let i = 0; i < 6; i++) bars.push(rect({ x: Math.round((rnd() - 0.5) * 120), y: 300 + rnd() * 1300, width: W, height: 12 + rnd() * 40, fill: i % 2 ? "#FF2E4D" : "#2EE6FF", opacity: 0.55 }));
    put("fx", bars, DROP + 4 * FR, 3 * FR);
  }
  put("fx", rect({ x: 0, y: 0, width: W, height: H, fill: "#FFFFFF", animate: [{ property: "opacity", keyframes: K([0, 0.95, EASE], [0.35, 0]) }] }), DROP + 4 * FR, 0.36);
  put("fx", rect({ x: 0, y: 0, width: W, height: H, fill: "#000000", blendMode: "screen",
    effects: [{ kind: "shader", params: { glsl: LEAK, amt: 0 } }],
    animate: [{ property: "effectParam", effectIndex: 0, effectParam: "amt", keyframes: K([0, 0, EASE], [0.3, 0.55, "hold"], [1.0, 0.55, EASE], [1.6, 0]) }] }), DROP + 0.1, 1.61);
  // blur transition into the trap: a single soft glitch
  {
    const bars = [];
    for (let i = 0; i < 4; i++) bars.push(rect({ x: Math.round((rnd() - 0.5) * 80), y: 400 + rnd() * 1100, width: W, height: 10 + rnd() * 26, fill: C.acc2, opacity: 0.35 }));
    put("fx", bars, 48.5, 3 * FR);
  }
  // CTA: darken the background a touch under the book, end hold
  put("legibility", rect({ x: 0, y: 0, width: W, height: H, fill: C.bk, animate: [{ property: "opacity", keyframes: K([0, 0, EASE], [0.5, 0.25, "hold"], [4.0, 0.25, EASE], [5.99, 0.45]) }] }), 51.0, 6.0);

  for (const k of ORDER) if (LAYERS[k]) p.compose(frame({ x: 0, y: 0, width: W, height: H, layout: "none" }, LAYERS[k]), { at: 0, dur: D.DUR, name: k });

  const mode = process.env.REEL_MODE || "frames";
  if (mode === "frames") {
    const only = process.env.REEL_TIMES ? process.env.REEL_TIMES.split(",").map(Number) : D.sheet;
    for (const t of only) await p.frame(t, `renders/f_${t.toFixed(2)}.png`);
  } else if (mode === "draft") {
    await p.render("renders/draft.mp4", { draft: true, concurrency: 4 });
  }
};
